/*******************************************************************************
 * __head.c
 *------------------------------------------------------------------------------
 * Header size allocation.
 * The '_headerAlloc' variable is used to reserve space for the TLV header.
 * This variable must NOT be defined as static, because if you do so
 * the compiler will remove the variable if the optimizations are set.
 * This file was automatically generated by IngeDev. Please, do not edit!
 ******************************************************************************/
const char _headerAlloc[%HEADER_SIZE%] =
{
%HEADER_CONTENT%
};
