@echo off
rem ****************************************************************************
rem * build.bat
rem *---------------------------------------------------------------------------
rem * Batch file used to build, rebuild or clean a project/subproject according
rem * to a configuration.
rem * This file was automatically generated by IngeDev. Please, do not edit!
rem ****************************************************************************
set CYGWIN=nodosfilewarning
if %1.==. goto Help
if %1==build goto RuleOk
if %1==rebuild goto RuleOk
if %1==clean goto RuleOk

goto Help

:RuleOk

if %2.==. goto Help
if %3.==. goto Help

set Path=%PATH_ENV%

rem ----------------------------------------------------------------------------
rem  The 'LIBRARY_PATH' variable is needed to build with GCC Win32 on
rem  Windows Vista
rem ----------------------------------------------------------------------------
set LIBRARY_PATH=%LIBRARY_PATH%

set MAKE_DEFAULT_OPTS=%MAKE_OPTS%
rem ----------------------------------------------------------------------------
rem - To build in verbose mode just left the 'MAKE_OPT_SILENT' variable to blank 
rem ----------------------------------------------------------------------------
set MAKE_OPT_SILENT=-s

set MAKE_OPTS=%MAKE_DEFAULT_OPTS% %MAKE_OPT_SILENT%

rem ----------------------------------------------------------------------------
rem - Check subproject is known and can be built, rebuilt or cleaned
rem ----------------------------------------------------------------------------

set SUBPROJECTS_LIST=all:%SUBPROJECTS_LIST%
set MEMO_SUBPROJECTS_LIST=%SUBPROJECTS_LIST%
set SUBPROJECT=

rem Check if subproject is known and can be built, rebuilt or cleaned
if not defined SUBPROJECTS_LIST goto End
:SubProjectLoop
set CHAR=%SUBPROJECTS_LIST:~0,1%
if "%CHAR%"==":" goto CheckSubproject
set SUBPROJECT=%SUBPROJECT%%CHAR%
goto SubProjectNextChar
:CheckSubproject
if "%2"=="%SUBPROJECT%" goto SubprojectOk
set SUBPROJECT=
:SubProjectNextChar
rem Next character
set SUBPROJECTS_LIST=%SUBPROJECTS_LIST:~1%
if not defined SUBPROJECTS_LIST goto LastSubProjectCheck
goto SubProjectLoop

:LastSubProjectCheck
if "%2"=="%SUBPROJECT%" goto SubprojectOk

echo The subproject '%2' does not exist! (available subprojects: '%MEMO_SUBPROJECTS_LIST%')
goto End

:SubprojectOk

rem ----------------------------------------------------------------------------
rem - Check configuration is known and can be built, rebuilt or cleaned
rem ----------------------------------------------------------------------------

set CONFIGS_LIST=all:%CONFIGS_LIST%
set MEMO_CONFIGS_LIST=%CONFIGS_LIST%
set CONFIG=

rem Check if config is known and can be built, rebuilt or cleaned
if not defined CONFIGS_LIST goto End
:ConfigLoop
set CHAR=%CONFIGS_LIST:~0,1%
if "%CHAR%"==":" goto CheckConfig
set CONFIG=%CONFIG%%CHAR%
goto ConfigNextChar
:CheckConfig
if "%3"=="%CONFIG%" goto ConfigOk
set CONFIG=
:ConfigNextChar
rem Next character
set CONFIGS_LIST=%CONFIGS_LIST:~1%
if not defined CONFIGS_LIST goto LastConfigCheck
goto ConfigLoop

:LastConfigCheck
if "%3"=="%CONFIG%" goto ConfigOk

echo The configuration '%3' does not exist! (available configurations: '%MEMO_CONFIGS_LIST%')
goto End

:ConfigOk

rem ----------------------------------------------------------------------------
rem - Build, rebuild or clean selected subproject for selected configuration
rem ----------------------------------------------------------------------------

if %3==all goto BuildAllConfigsAction

if %1==rebuild goto RebuildAction

%MAKEFILE_CALL%
goto End

:RebuildAction

%REBUILD_MAKEFILE_CALL%
goto End

:BuildAllConfigsAction

if %1==rebuild goto RebuildAllConfigsAction

%ALL_CONFIG_MAKEFILE_CALL%
goto End

:RebuildAllConfigsAction

%ALL_CONFIG_REBUILD_MAKEFILE_CALL%
goto End

:Help
echo. 
echo usage:
echo  build {rule_name} {subproject_name} {config_name} [{make_option}]
echo.
echo  rule_name       : the rule to launch ("build", "rebuild" or "clean") 
echo  subproject_name : the subproject to build, rebuild or clean ("all" for all subprojects) 
echo  config_name     : the configuration to build, rebuild or clean ("all" for all configurations)
echo  make_option     : additional make option (optional), useful for debug (-d or --debug)
echo.

:End
echo on
