@echo off
rem ****************************************************************************
rem * export.bat
rem *---------------------------------------------------------------------------
rem * Batch file used to build, rebuild or clean exported common modules 
rem * and libraries for selected configurations.
rem * This file was automatically generated by IngeDev. Please, do not edit!
rem ****************************************************************************
set CYGWIN=nodosfilewarning

if %1.==. goto Help
if %1==build goto RuleOk
if %1==rebuild goto RuleOk
if %1==clean goto RuleOk

goto Help

:RuleOk

if %2.==. goto Help
if %3.==. goto Help

if %4.==. goto Help
if %4==old goto ExportFormatOk
if %4==new goto ExportFormatOk

goto Help

:ExportFormatOk
if %5.==. goto Help
if %6.==. goto Help

if %4==old set Path=%PATH_ENV_ING5%
if %4==new set Path=%PATH_ENV%

rem ----------------------------------------------------------------------------
rem  The 'LIBRARY_PATH' variable is needed to build with GCC Win32 on
rem  Windows Vista
rem ----------------------------------------------------------------------------
set LIBRARY_PATH=%LIBRARY_PATH%

set MAKE_DEFAULT_OPTS=%MAKE_OPTS%
rem ----------------------------------------------------------------------------
rem - To build in verbose mode just left the 'MAKE_OPT_SILENT' variable to blank 
rem ----------------------------------------------------------------------------
set MAKE_OPT_SILENT=-s

set MAKE_OPTS=%MAKE_DEFAULT_OPTS% %MAKE_OPT_SILENT%

rem ----------------------------------------------------------------------------
rem - Check subprojects are known and can be exported
rem ----------------------------------------------------------------------------

set EXPORT_SUBPROJECTS_LIST=%SUBPROJECTS_LIST%
set MEMO_SUBPROJECTS_LIST=%EXPORT_SUBPROJECTS_LIST%
set SUBPROJECTS_FOR_MAKEFILE=
set BLANK_CHAR= 

if not "%EXPORT_SUBPROJECTS_LIST%"=="" goto ExportableSubprojects

echo No exportable subproject is available in the project!
goto End

:ExportableSubprojects
set SUBPROJECTS=%2
if %2==all set SUBPROJECTS=%EXPORT_SUBPROJECTS_LIST%

set INPUT_SUBPROJECTS_LIST=%SUBPROJECTS%

rem Check if subprojects are known and can be exported
if not defined EXPORT_SUBPROJECTS_LIST goto End
if not defined INPUT_SUBPROJECTS_LIST goto End

set INPUT_SUBPROJECT=
set SUBPROJECT=

:InputSubprojectLoop
set INPUT_CHAR=%INPUT_SUBPROJECTS_LIST:~0,1%
set EXPORT_SUBPROJECTS_LIST=%MEMO_SUBPROJECTS_LIST%
set SUBPROJECT=
if "%INPUT_CHAR%"==":" goto CheckSubprojectLoop
set INPUT_SUBPROJECT=%INPUT_SUBPROJECT%%INPUT_CHAR%
goto NextInputSubprojectChar

:CheckSubprojectLoop
set CHAR=%EXPORT_SUBPROJECTS_LIST:~0,1%
if "%CHAR%"==":" goto CheckSubproject
set SUBPROJECT=%SUBPROJECT%%CHAR%
goto NextSubprojectChar
:CheckSubproject
if "%INPUT_SUBPROJECT%"=="%SUBPROJECT%" goto SubprojectOk
set SUBPROJECT=
:NextSubprojectChar
rem Next character
set EXPORT_SUBPROJECTS_LIST=%EXPORT_SUBPROJECTS_LIST:~1%
if not defined EXPORT_SUBPROJECTS_LIST goto LastSubprojectCheck
goto CheckSubprojectLoop

:LastSubprojectCheck
if "%INPUT_SUBPROJECT%"=="%SUBPROJECT%" goto SubprojectOk

echo The subproject '%INPUT_SUBPROJECT%' does not exist or is not exportable! (available subprojects: '%MEMO_SUBPROJECTS_LIST%')
goto End

:SubprojectOk
set SUBPROJECTS_FOR_MAKEFILE=%SUBPROJECTS_FOR_MAKEFILE%%INPUT_SUBPROJECT%
if defined INPUT_SUBPROJECTS_LIST set SUBPROJECTS_FOR_MAKEFILE=%SUBPROJECTS_FOR_MAKEFILE%%BLANK_CHAR%
if not defined INPUT_SUBPROJECTS_LIST goto CheckSubprojectsDone

set INPUT_SUBPROJECT=
:NextInputSubprojectChar
rem Next input character
set INPUT_SUBPROJECTS_LIST=%INPUT_SUBPROJECTS_LIST:~1%
if not defined INPUT_SUBPROJECTS_LIST goto CheckSubprojectLoop
goto InputSubprojectLoop

:CheckSubprojectsDone

rem ----------------------------------------------------------------------------
rem - Check configurations are known and can be exported
rem ----------------------------------------------------------------------------

if %4==old goto IngeDev5Configs 
set EXPORT_CONFIGS_LIST=%CONFIGS_LIST_FOR_CURRENT_INGEDEV%
goto CheckConfigs

:IngeDev5Configs
set EXPORT_CONFIGS_LIST=%CONFIGS_LIST_FOR_INGEDEV5%

:CheckConfigs
set MEMO_CONFIGS_LIST=%EXPORT_CONFIGS_LIST%

set CONFIGS_FOR_MAKEFILE=

set CONFIGS=%3
if %3==all set CONFIGS=%EXPORT_CONFIGS_LIST%

set INPUT_CONFIGS_LIST=%CONFIGS%

rem Check if configs are known and can be exported
if not defined EXPORT_CONFIGS_LIST goto End
if not defined INPUT_CONFIGS_LIST goto End

set INPUT_CONFIG=
set CONFIG=

:InputConfigLoop
set INPUT_CHAR=%INPUT_CONFIGS_LIST:~0,1%
set EXPORT_CONFIGS_LIST=%MEMO_CONFIGS_LIST%
set CONFIG=
if "%INPUT_CHAR%"==":" goto CheckConfigLoop
set INPUT_CONFIG=%INPUT_CONFIG%%INPUT_CHAR%
goto NextInputConfigChar

:CheckConfigLoop
set CHAR=%EXPORT_CONFIGS_LIST:~0,1%
if "%CHAR%"==":" goto CheckConfig
set CONFIG=%CONFIG%%CHAR%
goto NextConfigChar
:CheckConfig
if "%INPUT_CONFIG%"=="%CONFIG%" goto ConfigOk
set CONFIG=
:NextConfigChar
rem Next character
set EXPORT_CONFIGS_LIST=%EXPORT_CONFIGS_LIST:~1%
if not defined EXPORT_CONFIGS_LIST goto LastConfigCheck
goto CheckConfigLoop

:LastConfigCheck
if "%INPUT_CONFIG%"=="%CONFIG%" goto ConfigOk

echo The configuration '%INPUT_CONFIG%' does not exist or is not exportable! (available configurations: '%MEMO_CONFIGS_LIST%')
goto End

:ConfigOk
set CONFIGS_FOR_MAKEFILE=%CONFIGS_FOR_MAKEFILE%%INPUT_CONFIG%
if defined INPUT_CONFIGS_LIST set CONFIGS_FOR_MAKEFILE=%CONFIGS_FOR_MAKEFILE%%BLANK_CHAR%
if not defined INPUT_CONFIGS_LIST goto CheckConfigsDone

set INPUT_CONFIG=
:NextInputConfigChar
rem Next input character
set INPUT_CONFIGS_LIST=%INPUT_CONFIGS_LIST:~1%
if not defined INPUT_CONFIGS_LIST goto CheckConfigLoop
goto InputConfigLoop

:CheckConfigsDone

rem ----------------------------------------------------------------------------
rem - Build, rebuild or clean and export selected subprojects for selected
rem - configurations
rem ----------------------------------------------------------------------------

if %1==rebuild goto RebuildAction

%MAKEFILE_CALL%
goto End

:RebuildAction

%REBUILD_MAKEFILE_CALL%
goto End

:Help
echo. 
echo usage:
echo  export {rule_name} {subproject_names} {config_names} {export_format} {export_path} {remove_symbols} [{make_option}]
echo.
echo  rule_name        : the rule to launch ("build", "rebuild" or "clean") 
echo  subproject_names : the subprojects to export ("all" for all subprojects)
echo                     WARNING: if there are severals subprojects, 
echo                              each one must be separated by ":"
echo                     Example: MyComMod:MyLib
echo  config_names     : the configurations to export ("all" for all configurations) 
echo                     WARNING: if there are severals configurations, 
echo                              each one must be separated by ":"
echo                     Example: MyConfig:AnotherConfig
echo  export_format    : "old" to export in old IngeDev format (IngeDev 5), 
echo                     "new" to export in current IngeDev format
echo                     WARNING: for old IngeDev format select one configuration
echo                              for the terminal and one configuration for the 
echo                              simulation, the two configurations must define
echo                              the same binary name (same terminal type, 
echo                              same country code and same domain number) to 
echo                              be valid.
echo  export_path      : the path where subprojects will be exported
echo  remove_symbols   : parameter used to remove or not debug symbols:
echo                     "true" to remove debug symbols,
echo                     "false" to keep debug symbols
echo                     WARNING: this parameter has no effect for ARM toolchain.
echo  make_option      : additional make option (optional), useful for debug (-d or --debug)
echo.

:End
echo on
