/*******************************************************************************
 * resources.h
 *------------------------------------------------------------------------------
 * resources include file.
 * This file was automatically generated by IngeDev. Please, do not edit!
 ******************************************************************************/
#ifndef _RESOURCES_H
#define _RESOURCES_H

//------------------------------------------------------------------------------
// String resources identifiers
//------------------------------------------------------------------------------
%STRING_RESOURCES_DEFINES%

//------------------------------------------------------------------------------
// Menu resources identifiers
//------------------------------------------------------------------------------
%MENU_RESOURCES_DEFINES%

//------------------------------------------------------------------------------
// Macro to make up the language codes to give to "amgSetLanguage" function
//------------------------------------------------------------------------------
#ifndef U32_MAKE_LANGUAGE_CODE
#define U32_MAKE_LANGUAGE_CODE(code) (code[1] << 8 | code[0])
#endif

//------------------------------------------------------------------------------
// Language constants to give to "amgSetLanguage" function
//------------------------------------------------------------------------------
%LANGUAGES_DEFINES%

#endif // _RESOURCES_H
