/*!
 ------------------------------------------------------------------------------
                  INGENICO Technical Software Department
 ------------------------------------------------------------------------------
 Copyright (c) 2013, Ingenico.
 28-32 boulevard de Grenelle 75015 Paris, France.
 All rights reserved.

  This source program is the property of INGENICO Company and may not be copied
  in any form or by any means, whether in part or in whole, except under license
  expressly granted by INGENICO company

  All copies of this program, whether in part or in whole, and
  whether modified or not, must display this and all other
  embedded copyright and ownership notices in full.
 ------------------------------------------------------------------------------

 Project : Easy Path to Dev
 Module  : PAR - Parameter Module

 @file      par.h
 @brief     This file provides the API for Parameter Module.
 @date      09/1/2013

 ------------------------------------------------------------------------------
 */
#ifndef __PAR_H__
#define __PAR_H__

#ifdef __cplusplus
extern "C" {
#endif

//This file is automatically generated from "param.pml" file
//Don't modify it manually!

  /** \addtogroup PAR Parameter Management Module
 *
 * @{
 */

  /** \weakgroup PAR_API PAR APIs
 *
 * @{
 */

  /** \weakgroup PAR_API_ErrorCodes PAR Error Codes
 *
 * @{
 */

#define PAR_OK 0 /**< No error encountered */
#define PAR_INVALID_HANDLE (-201) /**< Invalid parser */
#define PAR_BAD_PARAMETER (-202) /**< Bad input parameter (NULL pointer...) */
#define PAR_ERROR_PARSING (-203) /**< XML buffer is badly formatted */
#define PAR_ERROR_TAG_MISMATCH (-203) /**< Start tag and End tag of an element are not the same */
#define PAR_ERROR_SEVERAL_ROOT_TAGS (-205) /**< Several root tags have been found in the buffer */
#define PAR_ERROR_MEMORY (-206) /**< Not enough memory */
#define PAR_ERROR_FILE_ACCESS (-207) /**< Error when accessing the file */
#define PAR_TAG_NOT_FOUND (-208) /**< Tag not found */
#define PAR_UNKNOWN_ERROR (-209) /**< Unknown Error */
#define PAR_FILE_NOT_FOUND (-210) /**< File not found */
#define PAR_ACCESS_DENIED (-211) /**< Access Denied, Read-only access  */
#define PAR_NOT_INITIALIZED (-212) /**< Parameter data not Initialized, PAR_Import must be performed first */
#define PAR_INVALID_DATA (-213) /**< Invalid Parameter data being Set */
#define PAR_INVALID_DATA_LEN (-214) /**< Invalid Parameter data length being Set */

/** @} */


  enum eportNum
{
    COM0_PORT = 0,
    COM1_PORT = 1,
    COM2_PORT = 2,
    portNumEnd,
};

enum eportSpeed
{
    SPEED_1200 = 1200,
    SPEED_2400 = 2400,
    SPEED_4800 = 4800,
    SPEED_9600 = 9600,
    SPEED_19200 = 19200,
    SPEED_38400 = 38400,
    SPEED_57600 = 57600,
    SPEED_152000 = 152000,
    portSpeedEnd,
};


/** \weakgroup PAR_API_ParFunctions Par Functions
 *
 * @{
 */

/** \brief Copy the contents of the specified XML path and overwrite the contents of the existing
 * XML Parameter File. The parameter file will be initialized and the structure updated.
 *
 * \param[in] path The XML parameter path
 *
 * \return
 *      - \ref PAR_OK = Parameter file is parsed succesfully
 *      - \ref PAR_BAD_PARAMETER = Bad Input parameter.
 *      - \ref PAR_INVALID_HANDLE = Invalid Parser.
 *      - \ref PAR_ERROR_PARSING = XML Parameter file is badly formatted.
 *      - \ref PAR_ERROR_TAG_MISMATCH = Start tag and End tag of an element are not the same.
 *      - \ref PAR_ERROR_SEVERAL_ROOT_TAGS = Several root tags have been found in the buffer.
 *      - \ref PAR_ERROR_MEMORY = Not enough memory.
 *      - \ref PAR_ERROR_FILE_ACCESS = Error when accessing the file.
 *      - \ref PAR_UNKNOWN_ERROR = Unknown error occured.
 */
int PAR_Import(char *path);

/** \brief Copy the contents of the XML Parameter File into the specified XML path
 *
 * \param[in] path The XML parameter path
 *
 * \return
 *      - \ref PAR_OK = Parameter file is parsed succesfully
 *      - \ref PAR_NOT_INITIALIZED = Parameter data not Initialized, PAR_Import must be performed first.
 *      - \ref PAR_ERROR_FILE_ACCESS = Error when accessing the file.
 */
int PAR_Export(char *path);

/** \brief 
 * It contains number of com port
 * The parameter's datatype is SINGLE with READONLY access
 * \param[out] portNum pointer to the data to be obtained
 *
 * \return
 *      - \ref PAR_OK = Parameter file is parsed succesfully
 *      - \ref PAR_NOT_INITIALIZED = Parameter data not Initialized, PAR_Import must be performed first.
*/
int PAR_PortNumGet(int *portNum);

/** \brief 
 * It contains number of com port
 * The parameter's datatype is SINGLE with READONLY access
 * \param[in] portNum parameter value to be saved
 *
 * \return
 *      - \ref PAR_OK = Parameter file is parsed succesfully
 *      - \ref PAR_ACCESS_DENIED = Access Denied, Read-only access.
 *      - \ref PAR_NOT_INITIALIZED = Parameter data not Initialized, PAR_Import must be performed first.
 *      - \ref PAR_INVALID_DATA = Invalid Parameter data being Set.
 *      - \ref PAR_INVALID_DATA_LEN = Invalid Parameter data length being Set.
*/
int PAR_PortNumSet(enum eportNum portNum);

/** \brief 
 * It contains Speed of com port
 * The parameter's datatype is SINGLE with READONLY access
 * \param[out] portSpeed pointer to the data to be obtained
 *
 * \return
 *      - \ref PAR_OK = Parameter file is parsed succesfully
 *      - \ref PAR_NOT_INITIALIZED = Parameter data not Initialized, PAR_Import must be performed first.
*/
int PAR_PortSpeedGet(int *portSpeed);

/** \brief 
 * It contains Speed of com port
 * The parameter's datatype is SINGLE with READONLY access
 * \param[in] portSpeed parameter value to be saved
 *
 * \return
 *      - \ref PAR_OK = Parameter file is parsed succesfully
 *      - \ref PAR_ACCESS_DENIED = Access Denied, Read-only access.
 *      - \ref PAR_NOT_INITIALIZED = Parameter data not Initialized, PAR_Import must be performed first.
 *      - \ref PAR_INVALID_DATA = Invalid Parameter data being Set.
 *      - \ref PAR_INVALID_DATA_LEN = Invalid Parameter data length being Set.
*/
int PAR_PortSpeedSet(enum eportSpeed portSpeed);



/** @} */
/** @} */
/** @} */

#ifdef __cplusplus
}
#endif

#endif

