/*******************************************************************************
 * Calculator.h
 *------------------------------------------------------------------------------
 * widget id mapping header file
 * This file was automatically generated by IngeDev. Please, do not edit!
 *
 * This file is built from 'Calculator.iml' file which contains the mapping
 * between "idname" and "idval" for all widgets used in your application.
 * This allows to manage the interaction between the application business part
 * (written in "C" code) and the screen resource.
 *****************************************************************************/
#ifndef __CALCULATOR_WIDGET_MAPPINGS_H
#define __CALCULATOR_WIDGET_MAPPINGS_H

#define GL_ID_OPERAND_1 21
#define GL_ID_OPERATOR 22
#define GL_ID_OPERAND_2 23
#define GL_ID_RESULT 24

#endif //__CALCULATOR_WIDGET_MAPPINGS_H
