#ifdef __cplusplus
extern "C" {
#endif

#ifndef __TRACE_SAP_DEF_H_INCLUDED__
#define __TRACE_SAP_DEF_H_INCLUDED__

/*! @addtogroup KSFAM_DIAG
	* @{
 */ 

/*
======================================================================
					List of Enumerations
======================================================================
*/
typedef enum {
                   SAP_KERNEL_TRAP_RESET = 0x0000 ,		/*!< Kernel : Terminal Reset trace */
                    SAP_KERNEL_MEM_ALLOC = 0x0001 ,		/*!< Kernel : sysmalloc trace */
                     SAP_KERNEL_MEM_FREE = 0x0002 ,		/*!< Kernel : sysfree trace */
                        SAP_KERNEL_START = 0x0003 ,		/*!< Kernel : Start of telium system */
                        SAP_KERNEL_ERROR = 0x0004 ,		/*!< Kernel : Error found by kernel */
                      SAP_KERNEL_WARNING = 0x0005 ,		/*!< Kernel : Warning raise by kernel */
                        SAP_KERNEL_TRACE = 0x0006 ,		/*!< Kernel : trace */
                         SAP_LPROF_FRAME = 0x0050 ,   /*!< LPROF profiler frame trace*/
                  SAP_LPROF_TIMING_FRAME = 0x0051 ,   /*!< LPROF profiler timing frame trace*/
                  SAP_LPROF_MEMORY_FRAME = 0x0052 ,   /*!< LPROF profiler memory frame trace*/
                               SAP_POWER = 0x0100 ,		/*!< Power management controler : trace */
                     SAP_POWER_PMC_START = 0x0101 ,		/*!< Power management controler : Start of Power management controler  */
                   SAP_POWER_TIMER_START = 0x0102 ,		/*!< Power management controler : timer started */
                    SAP_POWER_TIMER_STOP = 0x0103 ,		/*!< Power management controler : timer stopped */
                     SAP_POWER_TIMER_EXP = 0x0104 ,		/*!< Power management controler : timer expiration */
                 SAP_LOADER_OBJ_REGISTER = 0x0200 ,		/*!< Object Loader : register new object */
                   SAP_LOADER_LOAD_APPLI = 0x0201 ,		/*!< Object Loader : application loaded */
                     SAP_LOADER_LOAD_DLL = 0x0202 ,		/*!< Object Loader : load DLL */
                     SAP_LOADER_LOAD_DRV = 0x0203 ,		/*!< Object Loader : load Driver */
                        SAP_LOADER_ERROR = 0x0204 ,		/*!< Object Loader : error */
                 SAP_LOADER_UNLOAD_APPLI = 0x0205 ,		/*!< Object Loader : unload application */
                   SAP_LOADER_UNLOAD_DLL = 0x0206 ,		/*!< Object Loader : unload DLL */
                SAP_LOADER_UNLOAD_DRIVER = 0x0207 ,		/*!< Object Loader : unload driver */
                        SAP_LOADER_CHECK = 0x0208 ,		/*!< Object Loader : check authenticity */
                     SAP_LOADER_OS2_LOAD = 0x0206 ,		/*!< Object Loader : system API */
                      SAP_MMU_INITIALIZE = 0x0300 ,		/*!< Memory Management Unit : initialize function */
                           SAP_MMU_ABORT = 0x0301 ,		/*!< Memory Management Unit : data or prefech abort */
                       SAP_FLASH_INSTALL = 0x0401 ,		/*!< Nand Flash Manager : install */
                         SAP_FLASH_START = 0x0402 ,		/*!< Nand Flash Manager : start */
                         SAP_FLASH_IDENT = 0x0403 ,		/*!< Nand Flash Manager : Nand identify */
                 SAP_FLASH_REPEATE_WRITE = 0x0404 ,		/*!< Nand Flash Manager : retry writting */
                         SAP_FLASH_WRITE = 0x0405 ,		/*!< Nand Flash Manager : write in flash */
                    SAP_FLASH_WRITE_PAGE = 0x0406 ,		/*!< Nand Flash Manager : write a page */
                          SAP_FLASH_READ = 0x0407 ,		/*!< Nand Flash Manager : read a page */
                        SAP_FLASH_FORMAT = 0x0408 ,		/*!< Nand Flash Manager : format flash */
                         SAP_FLASH_ERASE = 0x0409 ,		/*!< Nand Flash Manager : erase */
                       SAP_FLASH_GARBAGE = 0x040A ,		/*!< Nand Flash Manager : garbage collection */
                 SAP_FLASH_POWER_FAILURE = 0x040B ,		/*!< Nand Flash Manager : power failure detected */
                 SAP_FLASH_END_OF_OBJECT = 0x040C ,		/*!< Nand Flash Manager : seek end of file object */
                         SAP_FLASH_SPARE = 0x040D ,		/*!< Nand Flash Manager : read spare data */
                      SAP_FLASH_REGISTER = 0x040E ,		/*!< Nand Flash Manager : register */
                 SAP_FLASH_ADR_OF_OBJECT = 0x040F ,		/*!< Nand Flash Manager : seek address of object */
                        SAP_FLASH_UNLOAD = 0x0410 ,		/*!< Nand Flash Manager : unload registerd power failure data */
                    SAP_FLASH_INSTALL_OK = 0x041A ,		/*!< Nand Flash Manager : install OK */
                      SAP_FLASH_START_OK = 0x041B ,		/*!< Nand Flash Manager : start OK */
                  SAP_FLASH_GARBAGE_MOVE = 0x041C ,		/*!< Nand Flash Manager : garbage move page */
                  SAP_FLASH_GARBAGE_LINK = 0x041D ,		/*!< Nand Flash Manager : garbage link page */
                   SAP_FLASH_GARBAGE_END = 0x041E ,		/*!< Nand Flash Manager : end of garbage */
             SAP_FLASH_ADD_INVALID_BLOCK = 0x041F ,		/*!< Nand Flash Manager : bad block found */
        SAP_FLASH_MOVE_ALL_INVALID_BLOCK = 0x0420 ,		/*!< Nand Flash Manager : move block */
         SAP_FLASH_MOVE_EX_INVALID_BLOCK = 0x0420 ,		/*!< Nand Flash Manager : move block */
         SAP_FLASH_RESTORE_CONTEXT_START = 0x0421 ,		/*!< Nand Flash Manager : start restoring context at statup */
           SAP_FLASH_RESTORE_CONTEXT_END = 0x0422 ,		/*!< Nand Flash Manager : end or context retore */
         SAP_FLASH_RESTORE_CONTEXT_ERROR = 0x0423 ,		/*!< Nand Flash Manager : error in register data */
           SAP_FLASH_RESTART_AFTER_RESET = 0x0424 ,		/*!< Nand Flash Manager : restart OS after hardware reset */
                    SAP_FLASH_MOVE_BLOCK = 0x0425 ,		/*!< Nand Flash Manager : move block */
                    SAP_FLASH_READ_ERROR = 0x0426 ,		/*!< Nand Flash Manager : read error */
                         SAP_FLASH_REMAP = 0x0427 ,		/*!< Nand Flash Manager : remap Nand */
                SAP_FILE_SYSTEME_INSTALL = 0x0500 ,		/*!< File System : install */
                  SAP_FILE_SYSTEME_START = 0x0501 ,		/*!< File System : start */
                   SAP_FILE_SYSTEME_STOP = 0x0502 ,		/*!< File System : stop */
              SAP_FILE_SYSTEME_DSKCREATE = 0x0503 ,		/*!< File System : disk create */
                SAP_FILE_SYSTEME_DSKKILL = 0x0504 ,		/*!< File System : disk kill */
                  SAP_FILE_SYSTEME_MOUNT = 0x0505 ,		/*!< File System : mount a disk */
                SAP_FILE_SYSTEME_UNMOUNT = 0x0506 ,		/*!< File System : unmount a disk */
                 SAP_FILE_SYSTEME_FORMAT = 0x0507 ,		/*!< File System : format a disk */
               SAP_FILE_SYSTEME_READMODE = 0x0508 ,		/*!< File System : read mode */
                SAP_FILE_SYSTEME_CHGMODE = 0x0509 ,		/*!< File System : change mode */
                   SAP_FILE_SYSTEME_OPEN = 0x050A ,		/*!< File System : open a file */
                  SAP_FILE_SYSTEME_CLOSE = 0x050B ,		/*!< File System : close a file */
                   SAP_FILE_SYSTEME_FILE = 0x050C ,		/*!< File System : file access */
                  SAP_FILE_SYSTEME_WRITE = 0x050D ,		/*!< File System : write data */
                   SAP_FILE_SYSTEME_READ = 0x050E ,		/*!< File System : read data */
                  SAP_FILE_SYSTEME_TRUNC = 0x050F ,		/*!< File System : trunc a file */
                 SAP_FILE_SYSTEME_LENGTH = 0x0510 ,		/*!< File System : gets file length */
                   SAP_FILE_SYSTEME_SEEK = 0x0512 ,		/*!< File System : seek into a file */
                  SAP_FILE_SYSTEME_EXIST = 0x0513 ,		/*!< File System : check if file exist */
                   SAP_FILE_SYSTEME_TELL = 0x0514 ,		/*!< File System : tell function */
                 SAP_FILE_SYSTEME_RENAME = 0x0515 ,		/*!< File System : rename a file */
                 SAP_FILE_SYSTEME_UNLINK = 0x0516 ,		/*!< File System : unlink a file */
                SAP_FILE_SYSTEME_DSKFREE = 0x0517 ,		/*!< File System : Disk free */
                SAP_FILE_SYSTEME_DSKSIZE = 0x0518 ,		/*!< File System : disk size */
                SAP_FILE_SYSTEME_DSKLIST = 0x0519 ,		/*!< File System : disk list */
                  SAP_FILE_SYSTEME_FLUSH = 0x051A ,		/*!< File System : flush data */
                    SAP_FILE_SYSTEME_EOF = 0x051B ,		/*!< File System : eof function */
                SAP_FILE_SYSTEME_OPENDIR = 0x051C ,		/*!< File System : open dir */
                    SAP_FILE_SYSTEME_DIR = 0x051D ,		/*!< File System : read dir */
               SAP_FILE_SYSTEME_CLOSEDIR = 0x051E ,		/*!< File System : close dir */
                SAP_FILE_SYSTEME_READDIR = 0x051F ,		/*!< File System : read dir */
                SAP_FILE_SYSTEME_DIRFILE = 0x0520 ,		/*!< File System : read dir */
                SAP_FILE_SYSTEME_GARBAGE = 0x0521 ,		/*!< File System : garbage collection */
                 SAP_FILE_SYSTEME_LOCATE = 0x0522 ,		/*!< File System : seek a file */
                   SAP_FILE_SYSTEME_MOVE = 0x0523 ,		/*!< File System : move a file */  
              SAP_FILE_SYSTEME_DSKDELETE = 0x0524 ,		/*!< File System : disk delete */
            SAP_FILE_SYSTEME_WRITE_ERROR = 0x0525 ,		/*!< File System : write error */
             SAP_FILE_SYSTEME_READ_ERROR = 0x0526 ,		/*!< File System : read error */
            SAP_FILE_SYSTEME_MOUNT_ERROR = 0x0527 ,		/*!< File System : mount error */
             SAP_FILE_SYSTEME_OPEN_ERROR = 0x0528 ,		/*!< File System : open error */
             SAP_FILE_SYSTEME_INSTALL_OK = 0x0529 ,		/*!< File System : install OK */
               SAP_FILE_SYSTEME_START_OK = 0x052A ,		/*!< File System : start OK */		
                       SAP_MODEM_LINKPER = 0x0600 ,		/*!< modem : link device */
                          SAP_MODEM_OPEN = 0x0601 ,		/*!< modem : open device */
                         SAP_MODEM_CLOSE = 0x0602 ,		/*!< modem : close device */
                          SAP_MODEM_SEND = 0x0603 ,		/*!< modem : send data */
                       SAP_MODEM_RECEIVE = 0x0604 ,		/*!< modem : receive data */
                   SAP_MODEM_ESC_COMMAND = 0x0605 ,		/*!< modem : escape command */
                         SAP_MODEM_CD_UP = 0x0606 ,		/*!< modem : Carrier Detect is Up */
                       SAP_MODEM_CD_DOWN = 0x0607 ,		/*!< modem : Carrier Detect is down */
                       SAP_MODEM_CMD_BUF = 0x0608 ,		/*!< modem   */
                       SAP_MODEM_CMD_REJ = 0x0609 ,		/*!< modem   */
                   SAP_MODEM_SOFT_REBOOT = 0x060A ,		/*!< modem : reboot */
                   SAP_MODEM_INIT_VERROU = 0x060B ,		/*!< modem   */
                    SAP_MODEM_DEB_VERROU = 0x060C ,		/*!< modem   */
                    SAP_MODEM_FIN_VERROU = 0x060D ,		/*!< modem   */
                  SAP_MODEM_OUVRE_VERROU = 0x060E ,		/*!< modem   */
                  SAP_MODEM_FERME_VERROU = 0x060F ,		/*!< modem   */
                     SAP_MODEM_CONFIG_RQ = 0x0610 ,		/*!< modem   */
              SAP_MODEM_AIGUILLAGE_MODEM = 0x0611 ,		/*!< modem   */
                SAP_MODEM_AIGUILLAGE_COM = 0x0612 ,		/*!< modem   */
       SAP_MODEM_LINE_VOLTAGE_AVERAGE_OK = 0x0613 ,		/*!< modem   */
       SAP_MODEM_LINE_VOLTAGE_AVERAGE_KO = 0x0614 ,		/*!< modem   */
                          SAP_NTP_CREATE = 0x0700 ,		/*!< NTP Protocol : create file  */
                          SAP_NTP_REMOVE = 0x0701 ,		/*!< NTP Protocol : remove file */
                           SAP_NTP_TRACE = 0x0702 ,		/*!< NTP Protocol : trace */
                           SAP_USB_TRACE = 0x0800 ,		/*!< USB HOST : trace  */
                            SAP_USB_HOST = 0x0801 ,		/*!< USB HOST : trace */
                             SAP_USB_DEV = 0x0802 ,		/*!< USB DEV : trace */
                           SAP_USB_SETUP = 0x0810 ,		/*!< USB HOST : Setup transaction */
                             SAP_USB_OUT = 0x0811 ,		/*!< USB HOST : Out transaction */
                              SAP_USB_IN = 0x0812 ,		/*!< USB HOST : In transaction */
                             SAP_USB_HUB = 0x0813 ,		/*!< USB HOST : HUB */
                      SAP_USB_ADD_DEVICE = 0x0814 ,		/*!< USB HOST : add device */
                   SAP_USB_REMOVE_DEVICE = 0x0815 ,		/*!< USB HOST : remove device */
                  SAP_WO_UPD_HEADER_FILE = 0x0900 ,		/*!< File System - Write Once : update header */
                        SAP_WO_LOST_FILE = 0x0901 ,		/*!< File System - Write Once : file lost */
                        SAP_WO_BUF_FLUSH = 0x0902 ,		/*!< File System - Write Once : flush data */
                  SAP_WO_INIT_DISKS_USED = 0x0903 ,		/*!< File System - Write Once : disk found */
                         SAP_DEBUG_TRACE = 0x0A00 ,		/*!< Debug : trace */
                SAP_POWER_ACTIVITY_START = 0x0B00 ,		/*!< Power Management Controler : activity started */
                                SAP_GPRS = 0x0C00 ,		/*!< GPRS */
                                 SAP_CAM = 0x0D00 ,		/*!< Smart Card */
                              SAP_MORPHO = 0x0E00 ,		/*!< Morpho */
                    SAP_MORPHO_BIO_WRITE = 0x0E01 ,		/*!< Morpho */
                     SAP_MORPHO_BIO_READ = 0x0E02 ,		/*!< Morpho */
                 SAP_MORPHO_BIO_SEND_MSG = 0x0E03 ,		/*!< Morpho */
                  SAP_MORPHO_BIO_REC_MSG = 0x0E04 ,		/*!< Morpho */
                     SAP_MORPHO_ILV_SEND = 0x0E05 ,		/*!< Morpho */
                      SAP_MORPHO_ILV_REC = 0x0E06 ,		/*!< Morpho */
                      SAP_OEMC_INPUT_SIM = 0x0F00 ,		/*!< OEMC */
                        SAP_OEMC_IUC_USB = 0x0F01 ,		/*!< OEMC */
                            SAP_OEMC_IUC = 0x0F02 ,		/*!< OEMC */
                         SAP_OEMC_IUC_IN = 0x0F03 ,		/*!< OEMC */
                        SAP_OEMC_IUC_OUT = 0x0F04 ,		/*!< OEMC */
                              SAP_XMODEM = 0x1000 ,		/*!< Xmodem protocol */
                                 SAP_FTP = 0x1100 ,		/*!< FTP protocol */
                   UCMTRACE_INIT_M2OS_PT = 0x1201 ,		/*!< UCM module  */
                          UCMTRACE_ERROR = 0x1202 ,		/*!< UCM module */
                            UCMTRACE_ICC = 0x1203 ,		/*!< UCM module */
                           UCMTRACE_PPAD = 0x1204 ,		/*!< UCM module */
                            UCMTRACE_TRT = 0x1205 ,		/*!< UCM module */
                            UCMTRACE_PAY = 0x1206 ,		/*!< UCM module */
                        UCMTRACE_DISPLAY = 0x1207 ,		/*!< UCM module */
                        UCMTRACE_PRINTER = 0x1208 ,		/*!< UCM module */
                           UCMTRACE_HOST = 0x1209 ,		/*!< UCM module */
                         UCMTRACE_BUZZER = 0x120A ,		/*!< UCM module */
                            UCMTRACE_LED = 0x120B ,		/*!< UCM module */
                         UCMTRACE_DEVICE = 0x120C ,		/*!< UCM module */
                          UCMTRACE_MODEM = 0x120D ,		/*!< UCM module */
                              SAP_CB_EMV = 0x1300 ,		
                               SAP_MONEO = 0x1301 ,		
                             SAP_EMVTOOL = 0x1400 ,		
                              SAP_ETH_IN = 0x1500 ,		/*!< Ethernet driver */
                             SAP_ETH_OUT = 0x1501 ,		/*!< Ethernet driver */
                           SAP_ETH_TRACE = 0x1502 ,		/*!< Ethernet driver */
                         SAP_MEMORY_CARD = 0x1600 ,		/*!< MMC/SDcard/micro SD */
           SAP_MEMORY_CARD_COMMAND_START = 0x1601 ,		/*!< MMC/SDcard/micro SD */
             SAP_MEMORY_CARD_COMMAND_END = 0x1602 ,		/*!< MMC/SDcard/micro SD */
                       SAP_DISPLAY_COLOR = 0x1700 ,		/*!< Color display */
                       SAP_BOOSTER_TRACE = 0x1800 ,		/*!< Booster */
                    SAP_BOOSTER_DOWNLOAD = 0x1801 ,		/*!< Booster */
            SAP_BOOSTER_AUTHENTICATE_REQ = 0x1802 ,		/*!< Booster */
                  SAP_BOOSTER_SECURE_IUC = 0x1803 ,		/*!< Booster */
                               SAP_APPLE = 0x1900 ,     /*!< Driver d'IPxx (Iphone, IpodTouch ...) */
                         SAP_APPLE_WRITE = 0x1901 ,     /*!< Driver d'IPxx (Iphone, IpodTouch ...) */
                          SAP_APPLE_READ = 0x1902 ,     /*!< Driver d'IPxx (Iphone, IpodTouch ...) */
                       SAP_APPLE_REC_MSG = 0x1903 ,     /*!< Driver d'IPxx (Iphone, IpodTouch ...) */
                      SAP_APPLE_SEND_MSG = 0x1904 ,     /*!< Driver d'IPxx (Iphone, IpodTouch ...) */
                            SAP_INTERMEC = 0x1920 ,     /*!< Driver d'IPxx (Iphone, IpodTouch ...) / protocole ISCP */
                      SAP_INTERMEC_WRITE = 0x1921 ,     /*!< Driver d'IPxx (Iphone, IpodTouch ...) / protocole ISCP*/
                       SAP_INTERMEC_READ = 0x1922 ,     /*!< Driver d'IPxx (Iphone, IpodTouch ...) / protocole ISCP*/
                    SAP_INTERMEC_REC_MSG = 0x1923 ,     /*!< Driver d'IPxx (Iphone, IpodTouch ...) / protocole ISCP*/
                   SAP_INTERMEC_SEND_MSG = 0x1924 ,     /*!< Driver d'IPxx (Iphone, IpodTouch ...) / protocole ISCP*/
          SAP_INTERMEC_DOWNLOAD_FIRMWARE = 0x1925 ,     /*!< Driver d'IPxx (Iphone, IpodTouch ...) / protocole ISCP*/
          				 SAP_EXT_PRINTER = 0x1A00 ,     /*!< Driver external printer */
                        M2OS_DLL_CB2A_IN = 0x8006 ,		/*!< M2OS */
                       M2OS_DLL_CB2A_OUT = 0x8005 ,		/*!< M2OS */
                           M2OS_DLL_CB2A = 0x8000 ,		/*!< M2OS */
                         M2OS_DLL_EXTENS = 0x8100 ,		/*!< M2OS */
                         M2OS_DLL_LANGUE = 0x8200 ,		/*!< M2OS */
                          M2OS_DLL_LIBGR = 0x8300 ,		/*!< M2OS */
                          M2OS_DLL_PARAM = 0x8400 ,		/*!< M2OS */
                         M2OS_DLL_SAISIE = 0x8500 ,		/*!< M2OS */
                             M2OS_DLL_SV = 0x8600 ,		/*!< M2OS */
                         M2OS_DLL_DLLPSC = 0x8700 ,		/*!< M2OS */
                      M2OS_DLL_PROTOCOLE = 0x8800 ,		/*!< M2OS */
                        M2OS_DLL_PARTAGE = 0x8900 ,		/*!< M2OS */
                          M2OS_DLL_EMVSQ = 0x8A00 ,		/*!< M2OS */
                            M2OS_DLL_IAM = 0x8B00 ,		/*!< M2OS */
                         M2OS_DLL_PINPAD = 0x8C00 ,		/*!< M2OS */
                           M2OS_DLL_GPRS = 0x8D00 ,		/*!< M2OS */
                            M2OS_DLL_UMS = 0x8E00 ,		/*!< M2OS */
                             M2OS_SOURCE = 0x8F00 ,		/*!< M2OS */
                         M2OS_DEBIT_OVER = 0xA001 ,		/*!< M2OS */
                      M2OS_MORE_FUNCTION = 0xA002 ,		/*!< M2OS */
                   M2OS_IS_TIME_FUNCTION = 0xA003 ,		/*!< M2OS */
                      M2OS_TIME_FUNCTION = 0xA004 ,		/*!< M2OS */
               M2OS_TIME_FUNCTION_CHAINE = 0xA005 ,		/*!< M2OS */
                            M2OS_CONSULT = 0xA006 ,		/*!< M2OS */
                              M2OS_MCALL = 0xA007 ,		/*!< M2OS */
                              M2OS_STATE = 0xA008 ,		/*!< M2OS */
                          M2OS_AUTO_OVER = 0xA009 ,		/*!< M2OS */
                         M2OS_IS_EVOL_PG = 0xA00C ,		/*!< M2OS */
                     M2OS_IS_CHANGE_INIT = 0xA00D ,		/*!< M2OS */
                        M2OS_MODIF_PARAM = 0xA00E ,		/*!< M2OS */
                           M2OS_IS_ORDER = 0xA00F ,		/*!< M2OS */
                              M2OS_ORDER = 0xA010 ,		/*!< M2OS */
                        M2OS_IS_SUPPR_PG = 0xA011 ,		/*!< M2OS */
                      M2OS_IS_INSTALL_PG = 0xA012 ,		/*!< M2OS */
                          M2OS_GET_ORDER = 0xA013 ,		/*!< M2OS */
                         M2OS_IS_LIBELLE = 0xA014 ,		/*!< M2OS */
                          M2OS_IS_DELETE = 0xA015 ,		/*!< M2OS */
                        M2OS_EVOL_CONFIG = 0xA016 ,		/*!< M2OS */
                         M2OS_GIVE_MONEY = 0xA017 ,		/*!< M2OS */
                       M2OS_IDLE_MESSAGE = 0xA018 ,		/*!< M2OS */
                          M2OS_COM_EVENT = 0xA019 ,		/*!< M2OS */
                        M2OS_MODEM_EVENT = 0xA01A ,		/*!< M2OS */
                     M2OS_KEYBOARD_EVENT = 0xA01B ,		/*!< M2OS */
                      M2OS_GIVE_INFOS_CX = 0xA01C ,		/*!< M2OS */
                      M2OS_FILE_RECEIVED = 0xA01D ,		/*!< M2OS */
                   M2OS_MESSAGE_RECEIVED = 0xA01E ,		/*!< M2OS */
                        M2OS_CARD_INSIDE = 0xA01F ,		/*!< M2OS */
                     M2OS_GIVE_INTERFACE = 0xA020 ,		/*!< M2OS */
                          M2OS_IS_BIN_CB = 0xA021 ,		/*!< M2OS */
                   M2OS_IS_CARD_SPECIFIC = 0xA022 ,		/*!< M2OS */
                  M2OS_IS_FOR_YOU_BEFORE = 0xA023 ,		/*!< M2OS */
                           M2OS_GIVE_AID = 0xA024 ,		/*!< M2OS */
                   M2OS_IS_FOR_YOU_AFTER = 0xA025 ,		/*!< M2OS */
                M2OS_IS_CARD_EMV_FOR_YOU = 0xA026 ,		/*!< M2OS */
                          M2OS_DEBIT_EMV = 0xA027 ,		/*!< M2OS */
                      M2OS_DEBIT_NON_EMV = 0xA028 ,		/*!< M2OS */
                    M2OS_SELECT_FUNCTION = 0xA029 ,		/*!< M2OS */
                M2OS_SELECT_FUNCTION_EMV = 0xA02A ,		/*!< M2OS */
                   M2OS_GIVE_YOUR_DOMAIN = 0xA02B ,		/*!< M2OS */
                        M2OS_AFTER_RESET = 0xA02C ,		/*!< M2OS */
                         M2OS_SELECT_AID = 0xA02D ,		/*!< M2OS */
                        M2OS_DIAL_RECEPT = 0xA02E ,		/*!< M2OS */
                         M2OS_DIAL_EMISS = 0xA02F ,		/*!< M2OS */
                          M2OS_FALL_BACK = 0xA030 ,		/*!< M2OS */
                        M2OS_IS_LICENCED = 0xA031 ,		/*!< M2OS */
                       M2OS_TRACK_STREAM = 0xA032 ,		/*!< M2OS */
                M2OS_SELECT_AID_EXTENDED = 0xA033 ,		/*!< M2OS */
                       M2OS_CARD_REMOVAL = 0xA034 ,		/*!< M2OS */
                       M2OS_CARD_OUTSIDE = 0xA035 ,		/*!< M2OS */
         M2OS_GIVE_YOUR_SPECIFIC_CONTEXT = 0xA036 ,		/*!< M2OS */
                        M2OS_DEBIT_TPASS = 0xA037 ,		/*!< M2OS */
                   M2OS_SERVICE_SHORTCUT = 0xA038 ,		/*!< M2OS */
                      M2OS_APPEL_TELECOL = 0xA039 ,		/*!< M2OS */
                    M2OS_CLESS_GIVE_INFO = 0xA03A ,		/*!< M2OS */
                   M2OS_CLESS_IS_FOR_YOU = 0xA03B ,		/*!< M2OS */
                        M2OS_CLESS_DEBIT = 0xA03C ,		/*!< M2OS */
                    M2OS_CLESS_DEBIT_AID = 0xA03D ,		/*!< M2OS */
                  M2OS_CLESS_IS_SPECIFIC = 0xA03E ,		/*!< M2OS */
                       M2OS_CLESS_INSIDE = 0xA03F ,		/*!< M2OS */
                M2OS_GIVE_MONEY_EXTENDED = 0xA040 ,		/*!< M2OS */
                          M2OS_CLESS_END = 0xA041 ,		/*!< M2OS */
                          M2OS_M2OS_FORK = 0xA0B2 ,		/*!< M2OS */
                    BLUETOOTH_EVENT_TYPE = 0xAB00 ,		/*!< Bluetooth */	 
                       BLUETOOTH_BCSP_TX = 0xAB01 ,		/*!< Bluetooth */	 
                      BLUETOOTH_TRANSMIT = 0xAB02 ,		/*!< Bluetooth */	 
                       BLUETOOTH_BCSP_RX = 0xAB03 ,		/*!< Bluetooth */
                        BLUETOOTH_STRING = 0xAB04 ,		/*!< Bluetooth */
                       BLUETOOTH_RECEIVE = 0xAB05 ,		/*!< Bluetooth */
                       BLUETOOTH_PAYLOAD = 0xAB06 ,		/*!< Bluetooth */
                       BLUETOOTH_DELIVER = 0xAB07 ,		/*!< Bluetooth */
                     BLUETOOTH_DELIVERED = 0xAB08 ,		/*!< Bluetooth */
                             GPS_DRV_XXX = 0xAC00,      /*!< GPS Driver */
                          GPS_DRV_I2C_TX = 0xAC01,      /*!< GPS Driver */
                             GPS_DRV_YYY = 0xAC02,      /*!< GPS Driver */
                          GPS_DRV_I2C_RX = 0xAC03,      /*!< GPS Driver */
                          GPS_DRV_STRING = 0xAC04,      /*!< GPS Driver */
						  GPS_DLL_STRING = 0xAD00,      /*!< GPS DLL */
                              FEXCO_MAIN = 0xB600 ,		
                               FEXCO_TRA = 0xB601 ,		
                               FEXCO_CDC = 0xB602 ,		
                               FEXCO_SND = 0xB603 ,		
                               FEXCO_RCV = 0xB604 ,		
                                DCC_INIT = 0xB60A ,		
                         DCC_ELIGIBILITE = 0xB60B ,		
                               DCC_AUTOR = 0xB60C ,		
                                 DCC_MDC = 0xB60D ,		
                             SAP_DLL2EXE = 0xBC01 ,		
                   M2OS_DLL_EXTENS_STATE = 0xC000 ,		
                         SAP_SEC_GESTSCH = 0xCA00 ,		
                        SAP_SEC_SECURITY = 0xCA01 ,		
                SAP_DLLMDB_STATE_MACHINE = 0xCC00 ,		
                      SAP_DLLMDB_MESSAGE = 0xCC01 ,		
                      SAP_DLLMDB_POLLING = 0xCC02 ,		
                        SAP_DLLMDB_TIMER = 0xCC03 ,		
                          SAP_DLLMDB_LED = 0xCC04 ,		
                  SAP_DLLMDB_REP_POLLING = 0xCC05 ,		
                      SAP_DLLMDB_UCM_MSG = 0xCC06 ,		
                                SAP_WIFI = 0xF000 ,		/*!< WIFI */
                             SAP_CONNECT = 0xFE00 ,		
                      SAP_PPP_CONNECT_OK = 0xFE01 ,		/*!< PPP */		
                      SAP_PPP_CONNECT_KO = 0xFE02 ,		/*!< PPP */
                          SAP_DISCONNECT = 0xFE03 ,		
                         SAP_TCP_CONNECT = 0xFE04 ,		/*!< TCP/IP */
                      SAP_TCP_CONNECT_OK = 0xFE05 ,		/*!< TCP/IP */
                      SAP_TCP_CONNECT_KO = 0xFE06 ,		/*!< TCP/IP */
                      SAP_TCP_DISCONNECT = 0xFE07 ,		/*!< TCP/IP */
                         SAP_UDP_CONNECT = 0xFE08 ,		/*!< UDP */
                      SAP_UDP_CONNECT_OK = 0xFE09 ,		/*!< UDP */
                      SAP_UDP_CONNECT_KO = 0xFE0A ,		/*!< UDP */
                      SAP_UDP_DISCONNECT = 0xFE0B ,		/*!< UDP */
                         SAP_SSL_CONNECT = 0xFE0C ,		/*!< SSL */
                      SAP_SSL_CONNECT_OK = 0xFE0D ,		/*!< SSL */
                      SAP_SSL_CONNECT_KO = 0xFE0E ,		/*!< SSL */
                      SAP_SSL_DISCONNECT = 0xFE0F ,		/*!< SSL */
               SAP_SSL_CERTIFICATE_ERROR = 0xFE10 ,		/*!< SSL */
                                SAP_SEND = 0xFE11 ,		
                          SAP_SEND_ERROR = 0xFE12 ,		
                        SAP_WAIT_MESSAGE = 0xFE13 ,		
                             SAP_RECEIVE = 0xFE14 ,		
                             SAP_TIMEOUT = 0xFE15 ,		
                        SAP_GPRS_CONNECT = 0xFE16 ,		/*!< GPRS */
                     SAP_GPRS_CONNECT_OK = 0xFE17 ,		/*!< GPRS */
                     SAP_GPRS_CONNECT_KO = 0xFE18 ,		/*!< GPRS */
             SAP_TCP_CONNECT_IN_PROGRESS = 0xFE19 ,		/*!< TCP/IP */
                 SAP_TCP_CONNECT_ABORTED = 0xFE20 ,		/*!< TCP/IP */				
				 /* 0xFF00 to 0xFFFF are reserved for applications */
NB_TRACE_SAP_ID
} trace_sap_id_t ;

/*! @}  */ 


#endif   // __TRACE_SAP_DEF_H_INCLUDED__

#ifdef __cplusplus
}
#endif
