/*******************************************************************************
 * GetProcAddr.c
 *------------------------------------------------------------------------------
 * Dll Entry Point.
 * This file was automatically generated by IngeDev and must be filled out
 * by the developer.
 ******************************************************************************/
#include "sdk30.h"
#include "MyDllExport.h"

static const fct_desc_t tab_fct[]={
  {"OneBeep",        (void*)OneBeep},
  {"ManyBeep",       (void*)ManyBeep},
  {"InitVar",        (void*)initvar},
};


#define NB_FCT    sizeof(tab_fct)/sizeof(fct_desc_t)

void *GetProcAddress(char *name){
  unsigned int i;
#ifndef _ING_ARM_SDT_RELEASE
  static int initDone = 0;
  extern void InitVar();

  if (!initDone)
  {
    // Initialize global variables and global C++ objects.
    // This must be done only once.
    InitVar();
    initDone = 1;
  }
#endif
  
  for (i = 0; i < NB_FCT; i++){
    if (strcmp(name, tab_fct[i].fct_name) == 0)
      return tab_fct[i].fct;
  }
  return (void*)0;
}

