/*******************************************************************************
 * MyLibExport.h
 *------------------------------------------------------------------------------
 * Add in this header file, all the prototypes of exported functions
 * This file was automatically generated by IngeDev and must be filled out
 * by the developer.
 ******************************************************************************/

extern void OneBeepLIB(void);
extern int ManyBeepLIB(int);
