/*******************************************************************************
 * widgetMappings.h
 *------------------------------------------------------------------------------
 * widget id mapping header file
 * This file was automatically generated by IngeDev. Please, do not edit!
 *
 * This file is built from 'widgetMappings.iml' file which contains the mapping
 * between "idname" and "idval" for all widgets used in your application.
 * This allows to manage the interaction between the application business part
 * (written in "C" code) and the screen resource.
 *****************************************************************************/
#ifndef __WIDGET_MAPPINGS_H
#define __WIDGET_MAPPINGS_H

#define DATE_SCREEN_EDIT_DATE 1
#define DATE_SCREEN_BUTTON_OK 2
#define GENERIC_BUTTON_CANCEL 3
#define GL_ID_MR 4
#define GL_ID_MRS 5
#define GL_ID_FIRST_NAME 6
#define GL_ID_LAST_NAME 7
#define GL_ID_BIRTH_DAY 8
#define GL_ID_MARRIED 9
#define GL_ID_OK 10
#define GL_ID_CANCEL 11
#define GL_ID_OPERATION_1 100
#define GL_ID_OPERATION_2 101
#define ID_INCLUDE_12 12
#define ID_INCLUDE_13 13

#endif //__WIDGET_MAPPINGS_H
