/** 
 * \file Main.c
 *
 * Application entry point.
 * This file was automatically generated by IngeDev and must be filled out
 * by the developer.
 */

#include "SDK30.H"
#include "etat.h"

// ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
// Prototype declaration to be used with INCENDO (replacing 'more_function' declared in SDK file 'etat.h').
// This new prototype can be used with SDK version >= 6.5.
// ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
// extern int more_function_ext(NO_SEGMENT no, S_ETATOUT *in, void *out);

/** 
 * Application has to call ServiceRegister for each service with a same 
 *  address Main and using predefined service number.
 * \param    size (I-) data size.
 * \param    data (I-) contains data needed between the Manager and application regarding services.
 * 
 * \return service call status.
 *
 * \see sdk30.h
 *      etat.h
 */
int Main(unsigned int size, StructPt *data)
{
  unsigned short No;
  int            ret=FCT_OK;

  No=ApplicationGetCurrent();
  switch(data->service)
  {
    case AFTER_RESET :
	  ret = after_reset(No,NULL,&data->Param.AfterReset.param_out);
	  break;
    case MORE_FUNCTION :
	  ret = more_function(No,&data->Param.MoreFunction.param_in,NULL);
	  break;
    case IS_TIME_FUNCTION :
	  ret = is_time_function(No,NULL,&data->Param.IsTimeFunction.param_out);
	  break;
    case TIME_FUNCTION: // Activated every minute, to execute automatic periodic functions
      ret = time_function(No, NULL, NULL);
      break;
    case CONSULT :
	  ret = consult(No,NULL,NULL);
	  break;
    case MCALL :
	  ret = mcall(No,NULL,NULL);
	  break;
    case STATE :
	  ret = state(No,NULL,NULL);
	  break;
    case IS_NAME :
	  ret = is_name(No,NULL,&data->Param.IsName.param_out);
	  break;
    case IS_NAME_EXTENDED :
	  ret = is_name_extended(No,NULL,&data->Param.IsNameExtended.param_out);
	  break;
    case IS_STATE :
	  ret = is_state(No,NULL,&data->Param.IsState.param_out);
	  break;
    case IS_EVOL_PG :
	  ret = is_evol_pg(No,NULL,&data->Param.IsEvolPg.param_out);
	  break;
    case IS_CHANGE_INIT :
	  ret = is_change_init(No,NULL,&data->Param.IsChangeInit.param_out);
	  break;
    case MODIF_PARAM :
	  ret = modif_param(No,&data->Param.ModifParam.param_in,NULL);
	  break;
    case IS_DELETE :
	  ret = is_delete(No,NULL,&data->Param.IsDelete.param_out);
	  break;
    case IDLE_MESSAGE :
	  ret = idle_message(No,NULL,NULL);
	  break;
    case KEYBOARD_EVENT :
	  ret = keyboard_event(No,&data->Param.KeyboardEvent.param_in,&data->Param.KeyboardEvent.param_out);
	  break;
    case FILE_RECEIVED :
	  ret = file_received(No,&data->Param.FileReceived.param_in,NULL);
	  break;
    case MESSAGE_RECEIVED :
	  ret = message_received(No,&data->Param.MessageReceived.param_in,NULL);
	  break;
    case CARD_INSIDE :
	  ret = card_inside(No,&data->Param.CardInside.param_in,&data->Param.CardInside.param_out);
	  break;
    case IS_CARD_SPECIFIC :
	  ret = is_card_specific(No,&data->Param.IsCardSpecific.param_in,&data->Param.IsCardSpecific.param_out);
	  break;
    case IS_FOR_YOU_AFTER :
	  ret = is_for_you_after(No,&data->Param.IsForYouAfter.param_in,&data->Param.IsForYouAfter.param_out);
	  break;
    case DEBIT_NON_EMV :
	  ret = debit_non_emv(No,&data->Param.DebitNonEmv.param_in,&data->Param.DebitNonEmv.param_out);
	  break;
    case GIVE_YOUR_DOMAIN :
	  ret = give_your_domain(No,NULL,&data->Param.GiveYourType.param_out);
	  break;
    case GIVE_YOUR_SPECIFIC_CONTEXT :
	  ret = give_your_specific_context(No,NULL,&data->Param.GiveYourSpecificContext.param_out);
	  break;
    case DEBIT_OVER :
    case CARD_REMOVAL :
    case TIME_FUNCTION_CHAINE :
    case IS_ORDER :
    case ORDER :
    case IS_SUPPR_PG :
    case IS_INSTALL_PG :
    case GET_ORDER :
    case IS_LIBELLE :
    case EVOL_CONFIG :
    case GIVE_MONEY :
    case COM_EVENT :
    case MODEM_EVENT :
    case GIVE_INFOS_CX :
    case GIVE_INTERFACE :
    case IS_BIN_CB :
    case IS_CARD_EMV_FOR_YOU :
    case DEBIT_EMV :
    case SELECT_AID :
    case SELECT_AID_EXTENDED :
    case FALL_BACK :
    case IS_LICENCED :
    case TRACK_STREAM :
    case CARD_OUTSIDE :
	case APPEL_TELECOLLECTE :
	case CLESS_GIVE_INFO :
	case CLESS_IS_FOR_YOU :
	case CLESS_DEBIT :
	case CLESS_DEBIT_AID :
	case CLESS_IS_SPECIFIC :
	case CLESS_INSIDE :
    case GIVE_MONEY_EXTENDED :
    case PRINTER_IDLE_STATUS :
    case PINPAD_IDLE_STATUS :
    case CLESS_IDLE_STATUS :
    case GET_IDLE_STATE_PARAMETER :
    case GET_AMOUNT_STATE_PARAMETER :
    case START_OF_TRANSACTION :
    case END_OF_TRANSACTION :
    case SELECT_CARD_HOLDER :
    case SELECT_MERCHANT :
    case CASH_CARD_REMOVAL :
    case MAINT_INIT :
    case MAINT_PRINT :
    case DEBIT_IAM :
    case AUTO_OVER :
    case IS_FOR_YOU_BEFORE :
    case GIVE_AID :
    case CAISSE_DIVERS_1 :
    case DEBIT_TPASS :
    case SELECT_FUNCTION :
    case SELECT_FUNCTION_EMV :
	  break;
  }
  return(ret);
}
