// #LANGUAGE FR
// #FONFILE /SYSTEM/ISO1.SGN
// #MSGCODING ISO8859
// #FILETYPE 1
// #APPLITYPE B3BC

#message 1 MSG_READING_USB_KEY "Lecture Clé USB..."
#message 2 MSG_ERR_NO_FILE_FOUND "Aucun Fichier\n Trouvé !!"
#message 3 MSG_ERR_BMP_DLL_NOT_FOUND "Aucune image ne sera\n       affichée\n     DLL introuvable"
#message 4 MSG_ERR_JPG_DLL_NOT_FOUND "Les images JPG ne seront\n          pas affichées\n          DLL introuvable"
#message 5 MSG_ERR_PNG_DLL_NOT_FOUND "Les images PNG ne seront\n          pas affichées\n          DLL introuvable"
#message 6 MSG_APP_MENU_TITLE "Image Loader"
#message 7 MSG_ERR_USB_NOT_PLUGGED "USB non inseré"
#message 8 MSG_IMAGE_ID "IMAGE %d SUR %d"
#message 9 MSG_MENU_TITLE "Menu"
#message 10 MSG_ERR_OUT_OF_MEMORY "Memoire du Terminal pleine"
#message 11 MSG_ERR_IMPOSSIBLE_OPERATION "Opération impossible"
#message 12 MSG_IDEL_SCREEN_SAVED "Définie comme écran de veille"
#message 13 MSG_PLEASE_WAIT "Veuillez attendre..."
#message 14 MSG_ANIMATION_DEFINED_SAVED "Définie comme écran animé"
#message 15 MSG_ERR_IMAGE_NOT_SAVED "Image non sauvegardée"
#message 16 MSG_IMAGE_SAVED "Image Sauvegardée"
#message 17 MSG_PROMPT_DELETE_CONFIRMATION "Confirmer la suppression :"
#message 18 MSG_PROMPT_VALIDATION "Appuyer sur VERT pour valider"
#message 19 MSG_PROMPT_CANCEL "Appuyer sur ROUGE pour annuler"
#message 20 MSG_IMAGE_DELETED "Image supprimée..."
#message 21 MSG_ERR_IMAGE_EXISTS "L'image existe déjà"
#message 22 MSG_ERR_EMPTY_TERMINAL "Terminal vide"
#message 23 MSG_ERR_INVALID_FORMAT "Format d'image invalide"
#message 24 MSG_ANIMATION_DELETED "Animation supprimée..."
#message 25 MSG_ERR_ANIMATION_EXISTS "Animation déjà existante"
#message 26 MSG_MENU_L1_LOAD_FROM_MEDIA "Import"
#message 27 MSG_MENU_L11_FROM_USB "A partir de l'USB"
#message 28 MSG_MENU_L12_FROM_USD "A partir du micro SD"
#message 29 MSG_MENU_L2_BROWSE_TERMINAL "Parcourir Terminal"
#message 30 MSG_MENU_L3_SETTINGS "Paramètres"
#message 31 MSG_MENU_L31_HIDE_SREENSAVER "Masquer Ecran Veille"
#message 32 MSG_MENU_L31_SHOW_SREENSAVER "Afficher Ecran Veille"
#message 33 MSG_MENU_L32_LANGUAGE_CHOICE "Choix langue"
#message 34 MSG_MENU_L33_PREVIEW "Prévisualisation"
#message 35 MSG_MENU_L331_PREVIEW_2IMG "2 Images / Ecran"
#message 36 MSG_MENU_L332_PREVIEW_4IMG "4 Images / Ecran"
#message 37 MSG_MENU_L333_PREVIEW_6IMG "6 Images / Ecran"
#message 38 MSG_MENU_L334_PREVIEW_8IMG "8 Images / Ecran"
#message 39 MSG_MENU_L34_ERASE_IMAGES "Supprimer images"
#message 40 MSG_MENU_L35_PASSWORD "Mot de Passe"
#message 41 MSG_MENU_L351_ENABLE_PASSWORD "Activation"
#message 42 MSG_MENU_L351_DISABLE_PASSWORD "Désactivation"
#message 43 MSG_MENU_L352_CHANGE_PASSWORD "Changement"
#message 44 MSG_PROMPT_NEW_PASSWORD "Nouveau mot de passe:"
#message 45 MSG_PROMPT_CURRENT_PASSWORD "Tapez le mot de passe:"
#message 46 MSG_ERR_BAD_PASSWORD "Mot de passe incorrect"
#message 47 MSG_ANIMATION_SAVED "Animation sauvegardée"
#message 48 MSG_ERR_ANIMATION_NOT_SAVED "Animation non sauvegardée"
#message 49 MSG_ERR_INVALID_ANIMATION_FORMAT "Format d'animation invalide"
#message 50 MSG_MENU_SET_IMAGE_IDLE_SCREEN "Ecran de veille"
#message 51 MSG_MENU_SAVE_IMAGE "Enregistrer l'image"
#message 52 MSG_MENU_DELETE_IMAGE "Supprimer l'image"
#message 53 MSG_MENU_SET_ANIMATION_IDLE_SCREEN "Ecran animé"
#message 54 MSG_MENU_SAVE_ANIMATION "Enregistrer Animation"
#message 55 MSG_MENU_DELETE_ANIMATION "Supprimer Animation"
#message 56 MSG_MENU_L36_REMOTE_UPDATE "Mise à jour distante"
#message 57 MSG_ERR_UPDATE_CONNECTION "Erreur connexion"
#message 58 MSG_PROMPT_DELETE_ANIMATION "Confirmer la suppression\n                               (Animation écran de veille)"
#message 59 MSG_PROMPT_DELETE_IMAGE "Confirmer la suppression \n                               (Image écran de veille)"
#message 60 MSG_ERR_NO_ANIMATION_IMAGE_DEFINED "Aucune image ou\n  Animation définie"
