// #LANGUAGE SP
// #FONFILE /SYSTEM/ISO1.SGN
// #MSGCODING ISO8859
// #FILETYPE 1
// #APPLITYPE B3BC

#message 1 MSG_READING_USB_KEY "Leyendo mem. USB"
#message 2 MSG_ERR_NO_FILE_FOUND "¡No se encontraron\n archivos!"
#message 3 MSG_ERR_BMP_DLL_NOT_FOUND "No aparece ninguna\n imagen,\n DLL no encontrada"
#message 4 MSG_ERR_JPG_DLL_NOT_FOUND "Las imágenes JPG\n no se mostrarán,\n DLL no encontrada"
#message 5 MSG_ERR_PNG_DLL_NOT_FOUND "Las imágenes PNG\n no se mostrarán,\n DLL no encontrada"
#message 6 MSG_APP_MENU_TITLE "Image Loader"
#message 7 MSG_ERR_USB_NOT_PLUGGED "USB no se ha insertado"				
#message 8 MSG_IMAGE_ID "Imagen %d de %d"
#message 9 MSG_MENU_TITLE "Menú"
#message 10 MSG_ERR_OUT_OF_MEMORY "Memoria llena"
#message 11 MSG_ERR_IMPOSSIBLE_OPERATION "Operación imposible"
#message 12 MSG_IDEL_SCREEN_SAVED "Pantalla de reposo establecida"
#message 13 MSG_PLEASE_WAIT "Por favor espere ..."
#message 14 MSG_ANIMATION_DEFINED_SAVED "Definida(como)animación de reposo"
#message 15 MSG_ERR_IMAGE_NOT_SAVED "Imagen no guardada"
#message 16 MSG_IMAGE_SAVED "Imagen guardada"
#message 17 MSG_PROMPT_DELETE_CONFIRMATION "Confirmar eliminación:"
#message 18 MSG_PROMPT_VALIDATION "Pulse la tecla VERDE para confirmar"
#message 19 MSG_PROMPT_CANCEL "Pulse la tecla ROJA para cancelar"
#message 20 MSG_IMAGE_DELETED "Imagen eliminada..."
#message 21 MSG_ERR_IMAGE_EXISTS "La imagen ya existe"
#message 22 MSG_ERR_EMPTY_TERMINAL "Memoria vacía"
#message 23 MSG_ERR_INVALID_FORMAT "No válido tamaño de la imagen"
#message 24 MSG_ANIMATION_DELETED "Animación suprimida..."
#message 25 MSG_ERR_ANIMATION_EXISTS "La animación ya existe"
#message 26 MSG_MENU_L1_LOAD_FROM_MEDIA "Importar"
#message 27 MSG_MENU_L11_FROM_USB "Desde el USB"
#message 28 MSG_MENU_L12_FROM_USD "Desde una micro SD"
#message 29 MSG_MENU_L2_BROWSE_TERMINAL "Examinar Terminal"
#message 30 MSG_MENU_L3_SETTINGS "Parámetros"
#message 31 MSG_MENU_L31_HIDE_SREENSAVER "Sin pantalla de reposo"
#message 32 MSG_MENU_L31_SHOW_SREENSAVER "Con pantalla de reposo"
#message 33 MSG_MENU_L32_LANGUAGE_CHOICE "Selección de idioma"
#message 34 MSG_MENU_L33_PREVIEW "Vista previa"
#message 35 MSG_MENU_L331_PREVIEW_2IMG "2 fotos/pantalla"
#message 36 MSG_MENU_L332_PREVIEW_4IMG "4 fotos/pantalla"
#message 37 MSG_MENU_L333_PREVIEW_6IMG "6 fotos/pantalla"
#message 38 MSG_MENU_L334_PREVIEW_8IMG "8 fotos/pantalla"
#message 39 MSG_MENU_L34_ERASE_IMAGES "Eliminar las imágenes"
#message 40 MSG_MENU_L35_PASSWORD "Contraseña"
#message 41 MSG_MENU_L351_ENABLE_PASSWORD "Activación"
#message 42 MSG_MENU_L351_DISABLE_PASSWORD "Desactivación"
#message 43 MSG_MENU_L352_CHANGE_PASSWORD "Cambiar contraseña"
#message 44 MSG_PROMPT_NEW_PASSWORD "Nueva contraseña"
#message 45 MSG_PROMPT_CURRENT_PASSWORD "Introduzca la contraseña:"
#message 46 MSG_ERR_BAD_PASSWORD "Contraseña incorrecta"
#message 47 MSG_ANIMATION_SAVED "Animación guardada"
#message 48 MSG_ERR_ANIMATION_NOT_SAVED "Animáción no guardada"
#message 49 MSG_ERR_INVALID_ANIMATION_FORMAT "Formato de animación no válido"
#message 50 MSG_MENU_SET_IMAGE_IDLE_SCREEN "Screen Saver"
#message 51 MSG_MENU_SAVE_IMAGE "Guardar imagen"
#message 52 MSG_MENU_DELETE_IMAGE "Eliminar imagen"
#message 53 MSG_MENU_SET_ANIMATION_IDLE_SCREEN "Animación de pantalla"
#message 54 MSG_MENU_SAVE_ANIMATION "Guardar la animación"
#message 55 MSG_MENU_DELETE_ANIMATION "Eliminar la animación"
#message 56 MSG_MENU_L36_REMOTE_UPDATE "Actualización remota"
#message 57 MSG_ERR_UPDATE_CONNECTION "Error de conexión ..."
#message 58 MSG_PROMPT_DELETE_ANIMATION "Confirmar eliminación \n                 (animación de reposo)"
#message 59 MSG_PROMPT_DELETE_IMAGE "Confirmar eliminación \n                (imagen de reposo)"
#message 60 MSG_ERR_NO_ANIMATION_IMAGE_DEFINED "No hay imágenes\n o animación definidas"
