// #LANGUAGE EN
// #FONFILE /LOCAL/MANAGER.SGN
// #MSGCODING ISO8859
// #FILETYPE 1
// #APPLITYPE B3BC

#message 1 MSG_READING_USB_KEY "Reading USB Key..."
#message 2 MSG_ERR_NO_FILE_FOUND "No file found"
#message 3 MSG_ERR_BMP_DLL_NOT_FOUND "No image will be\n       displayed\n     DLL not found"
#message 4 MSG_ERR_JPG_DLL_NOT_FOUND "JPG images will not\n          be displayed\n         DLL not found"
#message 5 MSG_ERR_PNG_DLL_NOT_FOUND "PNG images will not\n          be displayed\n         DLL not found"
#message 6 MSG_APP_MENU_TITLE "Image Loader"
#message 7 MSG_ERR_USB_NOT_PLUGGED "USB not plugged "
#message 8 MSG_IMAGE_ID "PICTURE %d FROM %d"
#message 9 MSG_MENU_TITLE "Menu"
#message 10 MSG_ERR_OUT_OF_MEMORY "Out of memory"
#message 11 MSG_ERR_IMPOSSIBLE_OPERATION "Operation not possible !!"
#message 12 MSG_IDEL_SCREEN_SAVED "Saved as Idle Screen"
#message 13 MSG_PLEASE_WAIT "Please wait..."
#message 14 MSG_ANIMATION_DEFINED_SAVED "Saved as Animated Screen"
#message 15 MSG_ERR_IMAGE_NOT_SAVED "Picture not saved"
#message 16 MSG_IMAGE_SAVED "Picture saved"
#message 17 MSG_PROMPT_DELETE_CONFIRMATION "Confirm Deletion :"
#message 18 MSG_PROMPT_VALIDATION "Press Green to Validate"
#message 19 MSG_PROMPT_CANCEL "Press RED to Cancel"
#message 20 MSG_IMAGE_DELETED "Picture deleted..."
#message 21 MSG_ERR_IMAGE_EXISTS "Picture already Exists"
#message 22 MSG_ERR_EMPTY_TERMINAL "Terminal is empty"
#message 23 MSG_ERR_INVALID_FORMAT "Invalid picture format"
#message 24 MSG_ANIMATION_DELETED "Animation deleted..."
#message 25 MSG_ERR_ANIMATION_EXISTS "Animation already exists"
#message 26 MSG_MENU_L1_LOAD_FROM_MEDIA "Load From Media"
#message 27 MSG_MENU_L11_FROM_USB "From USB"
#message 28 MSG_MENU_L12_FROM_USD "From micro SD"
#message 29 MSG_MENU_L2_BROWSE_TERMINAL "Browse Terminal"
#message 30 MSG_MENU_L3_SETTINGS "Settings"
#message 31 MSG_MENU_L31_HIDE_SREENSAVER "Hide Screen Saver"
#message 32 MSG_MENU_L31_SHOW_SREENSAVER "SHOW Screen Saver"
#message 33 MSG_MENU_L32_LANGUAGE_CHOICE "Language Choice"
#message 34 MSG_MENU_L33_PREVIEW "Preview"
#message 35 MSG_MENU_L331_PREVIEW_2IMG "2 Images / Screen"
#message 36 MSG_MENU_L332_PREVIEW_4IMG "4 Images / Screen"
#message 37 MSG_MENU_L333_PREVIEW_6IMG "6 Images / Screen"
#message 38 MSG_MENU_L334_PREVIEW_8IMG "8 Images / Screen"
#message 39 MSG_MENU_L34_ERASE_IMAGES "Erase Images"
#message 40 MSG_MENU_L35_PASSWORD "Password"
#message 41 MSG_MENU_L351_ENABLE_PASSWORD "Activate"
#message 42 MSG_MENU_L351_DISABLE_PASSWORD "Deactivate"
#message 43 MSG_MENU_L352_CHANGE_PASSWORD "Change"
#message 44 MSG_PROMPT_NEW_PASSWORD "New password:"
#message 45 MSG_PROMPT_CURRENT_PASSWORD "Enter your password:"
#message 46 MSG_ERR_BAD_PASSWORD "Bad password"
#message 47 MSG_ANIMATION_SAVED "Animation saved"
#message 48 MSG_ERR_ANIMATION_NOT_SAVED "Animation not saved"
#message 49 MSG_ERR_INVALID_ANIMATION_FORMAT "Invalid Animation format"
#message 50 MSG_MENU_SET_IMAGE_IDLE_SCREEN "Idle Screen"
#message 51 MSG_MENU_SAVE_IMAGE "Save Picture"
#message 52 MSG_MENU_DELETE_IMAGE "Delete Picture"
#message 53 MSG_MENU_SET_ANIMATION_IDLE_SCREEN "Animated Screen"
#message 54 MSG_MENU_SAVE_ANIMATION "Save Animation"
#message 55 MSG_MENU_DELETE_ANIMATION "Delete Animation"
#message 56 MSG_MENU_L36_REMOTE_UPDATE "Remote update"
#message 57 MSG_ERR_UPDATE_CONNECTION "Connection error"
#message 58 MSG_PROMPT_DELETE_ANIMATION "Confirm Deletion\n                             (Idle Screen Animation)"
#message 59 MSG_PROMPT_DELETE_IMAGE "Confirm Deletion\n                             (Idle Screen Image)"
#message 60 MSG_ERR_NO_ANIMATION_IMAGE_DEFINED "No image or\n  Animation defined"
