/** \file Main.c
 *
 * Application entry point.
 * This file was automatically generated by IngeDev and must be filled out
 * by the developer.
 */

#include "SDK30.H"
#include "etat.h"


/** Application has to call ServiceRegister for each service with a same 
 *  address Main and using predefined service number.
 * \param    size (I-) 
 *    - data size.
 * \param    data (I-)
 *    - contains data needed between the Manager and application regarding services.
 * \return                                           
 *  service call status.
 * \header sdk30.h etat.h
 * \source main.c 
 */

int Main(unsigned int size, StructPt *data)
{
    unsigned short No;
    int            ret=FCT_OK;

    No=ApplicationGetCurrent();
    switch(data->service)
    {
        case AFTER_RESET :
            ret = after_reset(No,NULL,&data->Param.AfterReset.param_out);
            break;
        case DEBIT_OVER :
            break;
        case MORE_FUNCTION :
            ret = more_function(No,NULL,NULL);
            break;
        case IS_TIME_FUNCTION :
            break;
        case TIME_FUNCTION :
            break;
        case TIME_FUNCTION_CHAINE :
            break;
        case CONSULT :
            break;
        case MCALL :
            break;
        case STATE :
            break;
        case AUTO_OVER :
            break;
        case IS_NAME :
            ret = is_name(No,NULL,&data->Param.IsName.param_out);
            break;
        case IS_STATE :
            ret = is_state(No,NULL,&data->Param.IsName.param_out);
            break;
        case IS_EVOL_PG :
            break;
        case IS_CHANGE_INIT :
            break;
        case MODIF_PARAM :
            break;
        case IS_ORDER :
            break;
        case ORDER :
            break;
        case IS_SUPPR_PG :
            break;
        case IS_INSTALL_PG :
            break;
        case GET_ORDER :
            break;
        case IS_LIBELLE :
            break;
        case IS_DELETE :
            break;
        case EVOL_CONFIG :
            break;
        case GIVE_MONEY :
            break;
        case IDLE_MESSAGE :
            ret = idle_message(No,NULL,NULL);
            break;
        case COM_EVENT :
            ret = com_event(No,&data->Param.ComEvent.param_in,&data->Param.ComEvent.param_out);
            break;
        case MODEM_EVENT :
            break;
        case KEYBOARD_EVENT :
            ret = keyboard_event(No, &data->Param.KeyboardEvent.param_in, &data->Param.KeyboardEvent.param_out);
    		break;
        case GIVE_INFOS_CX :
            break;
        case FILE_RECEIVED :
            break;
        case MESSAGE_RECEIVED :
            break;
        case CARD_INSIDE :
            break;
        case GIVE_INTERFACE :
            break;
        case IS_BIN_CB :
            break;
        case IS_CARD_SPECIFIC :
            break;
        case IS_FOR_YOU_BEFORE :
            break;
        case GIVE_AID :
            break;
        case IS_FOR_YOU_AFTER :
            break;
        case IS_CARD_EMV_FOR_YOU :
            break;
        case DEBIT_EMV :
            break;
        case DEBIT_NON_EMV :
            break;
        case SELECT_FUNCTION :
            break;
        case SELECT_FUNCTION_EMV :
            break;
        case GIVE_YOUR_DOMAIN :
            ret = give_your_domain(No,NULL,&data->Param.GiveYourType.param_out);
            break;
    }
    return(ret);
}
