/*******************************************************************************
 * widgetMappings.h
 *------------------------------------------------------------------------------
 * widget id mapping header file
 * This file was automatically generated by IngeDev. Please, do not edit!
 *
 * This file is built from 'widgetMappings.iml' file which contains the mapping
 * between "idname" and "idval" for all widgets used in your application.
 * This allows to manage the interaction between the application business part
 * (written in "C" code) and the screen resource.
 *****************************************************************************/
#ifndef __WIDGET_MAPPINGS_H
#define __WIDGET_MAPPINGS_H


#endif //__WIDGET_MAPPINGS_H
