/** \file Entry.c
 *
 * Application entry point.
 * This file was automatically generated by IngeDev and must be filled out
 * by the developer.
 *                   
 * Purpose :
 *
 * Each time Manager calls an application, it generates only one service
 * call that reaches your application main with the corresponding service
 * number.
 *
 * List of routines in file :
 * - give_your_domain : Return application domain.
 * - after_reset : Application reset processing.
 * -  is_name : Report application name to Manager.
 * -  is_state : Return application status (initialise or not).
 * -  idle_message : Dedicated to display idle message.
 * -  more_function : Dedicated to navigation menus.
 * -  keyboard_event : Return key pressed.
 * -  state : Print terminal content.
 * -  consult : Print daily totals.
 * -  mcall : Print call schedule.
 * -  is_time_function : Need pheripherals at the next call time_function()
 * -  time_function : Allow automatic execution of periodic functions.
 * -  is_change_init : Conditions for changing manager parameters?
 * -  modif_param : Manager reports parameters changing.
 * -  is_evol_pg : Conditions for application downloading?
 * -  is_delete : Conditions for application deletion?
 * -  file_received : Manager reports parameters file received from LLT.
 * -  message_received : Inter application messaging.
 * -  is_card_specific : Card needs a specific process?
 * -  card_inside : Transaction in progress for a specific card.
 * -  is_for_you_before : Is chip card as an ISO 7816-3?
 * -  is_for_you_after : recognise mag, smc or man card in order to be a candidate.     
 * -  cless_give_info : contactless parameters for each contactless application.  
 * -  cless_debit_aid : contactless debit with AID allready selected.  
 * -  give_interface : Services registration and priority.
 * -  entry : Call by OS for recording services and opening DLL(s). 
 */


/////////////////////////////////////////////////////////////////
//// Includes ///////////////////////////////////////////////////

#include "ClessSample_Implementation.h"


/////////////////////////////////////////////////////////////////
//// Macros & preprocessor definitions //////////////////////////

#define SERVICES_LOW_PRIORITY			30
#define SERVICES_HIGH_PRIORITY			10
#define SERVICES_DEFAULT_PRIORITY		20


/////////////////////////////////////////////////////////////////
//// Static functions definition ////////////////////////////////

void entry(void);
static int select_function_emv_ (NO_SEGMENT no, S_TRANSIN *param_in, S_TRANSOUT *param_out);
static int Main_(unsigned int nSize, StructPt* pData);
static int give_your_domain_ (NO_SEGMENT no, S_INITPARAMOUT *param_out);
static int give_money_extended_ (NO_SEGMENT no , void * p1, S_MONEYOUT_EXTENDED * moneyout);
static int after_reset_ (NO_SEGMENT no, S_TRANSOUT *param_out);
static int is_name_(NO_SEGMENT no, S_ETATOUT *param_out);
static int is_state_(NO_SEGMENT no, S_ETATOUT *param_out);
static int idle_message_ (NO_SEGMENT no);
static int more_function_ (NO_SEGMENT no);
static int keyboard_event_ (NO_SEGMENT noappli,S_KEY *key_in,S_KEY *key_out);
static int state_ (NO_SEGMENT no);
//static int consult_ (NO_SEGMENT no);
//static int mcall_ (NO_SEGMENT no);
static int is_time_function_ (NO_SEGMENT no, S_ETATOUT *param_out);
//static int time_function_ (NO_SEGMENT no);
static int is_change_init_(NO_SEGMENT no, S_ETATOUT *param_out);
//static int modif_param_(NO_SEGMENT noappli, S_MODIF_P *param_in);
static int is_evol_pg_ (NO_SEGMENT no, S_ETATOUT *param_out);
static int is_delete_ (NO_SEGMENT no, S_DELETE *param_out);
static int file_received_ (NO_SEGMENT no, S_FILE *param_in);
static int message_received_ (NO_SEGMENT no, S_MESSAGE_IAM *param_in);
static int is_card_specific_ (NO_SEGMENT no, S_TRANSIN *param_in, S_ETATOUT *param_out);
//static int card_inside_ (NO_SEGMENT no, S_TRANSIN *param_in, S_TRANSOUT *param_out);
//static int is_for_you_after_ (NO_SEGMENT no, S_TRANSIN *param_in, S_CARDOUT *param_out);
//static int debit_non_emv_ (NO_SEGMENT no, S_TRANSIN * param_in, S_TRANSOUT * param_out);
static int give_your_specific_context_(const NO_SEGMENT AppliNum, S_SPECIFIC_CONTEXT* pParamOut);
///static int cless_give_info_ (NO_SEGMENT no, S_TRANSIN * param_in, S_CLESS_GIVEINFO * param_out);
///static int cless_debit_aid_ (NO_SEGMENT no, unsigned int nSize, void * pData);
///static int cless_end_ (NO_SEGMENT nAppliNum);
static int give_interface_ (unsigned short AppliNum, void* pParamIn, void* pParamOut);
static int custom_kernel_ (unsigned int nSize, void * pData);
static int de_kernel_ (unsigned int nSize, void * pData);
///static int custom_appli_selection_proc (unsigned int nSize, void * pData);
///static int custom_selection_gui (unsigned int nSize, void * pData);
///static void Customize_message(int size, InfosMSG_CUST *infoscust);
static void	Test_DLL_Security_Presence(void);


/////////////////////////////////////////////////////////////////

static service_desc_t ServicesStandard[] = {
	{ 0, AFTER_RESET, (SAP)Main_, SERVICES_DEFAULT_PRIORITY },
	{ 0, IDLE_MESSAGE, (SAP)Main_, 254},
	{ 0, IS_CARD_SPECIFIC, (SAP)Main_, SERVICES_DEFAULT_PRIORITY },
	{ 0, IS_CHANGE_INIT, (SAP)Main_, SERVICES_DEFAULT_PRIORITY },
	{ 0, IS_DELETE, (SAP)Main_, SERVICES_DEFAULT_PRIORITY },
	{ 0, IS_NAME, (SAP)Main_, SERVICES_DEFAULT_PRIORITY },
	{ 0, IS_STATE, (SAP)Main_, SERVICES_DEFAULT_PRIORITY },
	{ 0, GIVE_YOUR_DOMAIN, (SAP)Main_, SERVICES_DEFAULT_PRIORITY },
	{ 0, GIVE_MONEY_EXTENDED, (SAP)Main_, SERVICES_DEFAULT_PRIORITY },
	{ 0, MORE_FUNCTION, (SAP)Main_, SERVICES_DEFAULT_PRIORITY },
	{ 0, STATE, (SAP)Main_, SERVICES_DEFAULT_PRIORITY },
	{ 0, FILE_RECEIVED, (SAP)Main_, SERVICES_DEFAULT_PRIORITY },
	{ 0, SERVICE_CUSTOM_KERNEL, (SAP)custom_kernel_, SERVICES_DEFAULT_PRIORITY },
	{ 0, SERVICE_DE_KERNEL, (SAP)de_kernel_, SERVICES_DEFAULT_PRIORITY },
	{ 0, SELECT_FUNCTION_EMV, (SAP)Main_, SERVICES_DEFAULT_PRIORITY },
	{ 0, GIVE_YOUR_SPECIFIC_CONTEXT, (SAP)Main_, SERVICES_DEFAULT_PRIORITY },
	{ 0, KEYBOARD_EVENT, (SAP)Main_, SERVICES_DEFAULT_PRIORITY },
};


static service_desc_t ServicesUnattended[] = {
	{ 0, AFTER_RESET, (SAP)Main_, SERVICES_DEFAULT_PRIORITY },
	{ 0, IDLE_MESSAGE, (SAP)Main_, 254},
	{ 0, IS_CARD_SPECIFIC, (SAP)Main_, SERVICES_DEFAULT_PRIORITY },
	{ 0, IS_CHANGE_INIT, (SAP)Main_, SERVICES_DEFAULT_PRIORITY },
	{ 0, IS_DELETE, (SAP)Main_, SERVICES_DEFAULT_PRIORITY },
	{ 0, IS_NAME, (SAP)Main_, SERVICES_DEFAULT_PRIORITY },
	{ 0, IS_STATE, (SAP)Main_, SERVICES_DEFAULT_PRIORITY },
	{ 0, GIVE_YOUR_DOMAIN, (SAP)Main_, SERVICES_DEFAULT_PRIORITY },
	{ 0, GIVE_MONEY_EXTENDED, (SAP)Main_, SERVICES_DEFAULT_PRIORITY },
	{ 0, MORE_FUNCTION, (SAP)Main_, SERVICES_DEFAULT_PRIORITY },
	{ 0, STATE, (SAP)Main_, SERVICES_DEFAULT_PRIORITY },
	{ 0, FILE_RECEIVED, (SAP)Main_, SERVICES_DEFAULT_PRIORITY },
	{ 0, SERVICE_CUSTOM_KERNEL, (SAP)custom_kernel_, SERVICES_DEFAULT_PRIORITY },
	{ 0, SERVICE_DE_KERNEL, (SAP)de_kernel_, SERVICES_DEFAULT_PRIORITY },
	{ 0, SELECT_FUNCTION_EMV, (SAP)Main_, SERVICES_DEFAULT_PRIORITY },
	{ 0, GIVE_YOUR_SPECIFIC_CONTEXT, (SAP)Main_, SERVICES_DEFAULT_PRIORITY },
	{ 0, KEYBOARD_EVENT, (SAP)Main_, SERVICES_DEFAULT_PRIORITY },
	{ 0, COM_EVENT, (SAP)Main_, SERVICES_DEFAULT_PRIORITY },
	{ 0, MESSAGE_RECEIVED, (SAP)Main_, SERVICES_DEFAULT_PRIORITY },
};



static const char appName[] = "CLess";
static const char coldReset[] = "Cold Reset\nFrom ";
static const char warmReset[] = "Warm Reset\nFrom ";
static const char timeToCall[] = "Time to call\nFrom ";
static const char idleMsgPart1[] = "'1': Std txn";
static const char idleMsgPart2[] = "'2': Specific txn";
static const char idleMsgPart3[] = "'red': clean (torn)";
static const char szDate[] = "Date:%.2s/%.2s/%.2s  %.2s:%.2s\n";

static int gs_bCaKeyCheckingDone = FALSE;
static int gs_nHeaderEventMask;
static int g_bDllTpassLoaded = FALSE;


/////////////////////////////////////////////////////////////////
//// Functions //////////////////////////////////////////////////

static int give_money_extended_ (NO_SEGMENT no , void * p1, S_MONEYOUT_EXTENDED * moneyout)
{
  S_MONEYOUT_EXTENDED money_out;
 
  // Unused parameters
  (void)no;
  (void)p1;
  
  int n_NbMoney;
  S_MONEY_EXTENDED * ps_x_Money;

  memcpy (&money_out, moneyout, sizeof(S_MONEYOUT_EXTENDED));
  strcpy (money_out.etat_retour[money_out.nb_reponse].libelle , (char*)appName ) ;
  
  ClessSample_Parameters_GetMoneyExtended(&n_NbMoney, &ps_x_Money);
  memcpy(&money_out.etat_retour[money_out.nb_reponse].money[0], ps_x_Money, n_NbMoney * sizeof(S_MONEY_EXTENDED));

  money_out.etat_retour[money_out.nb_reponse].nb_money = n_NbMoney;
  money_out.nb_reponse++;
  memcpy ( moneyout , &money_out , sizeof(S_MONEYOUT_EXTENDED));
  return (FCT_OK) ;
}

/** Enable the refund in the Manager menu.
 * \param    param_out (-O) Eventually ends interrupted transaction
 * \return                                           
 *  STOP
 * \header sdk30.h
 * \source entry.c 
*/
static int select_function_emv_ (NO_SEGMENT no, S_TRANSIN *param_in, S_TRANSOUT *param_out)
{
	(void)param_in;
	param_out->noappli     = no;
	param_out->rc_payment  = 0x01; //PAIEM_KO;

	return (STOP);
}



/** Ask application to define its working environment, Manager will select 
 *  common parameters set and adapt its internal processing.
 * \param    param_out (-O) 
 *    - application_type :   
 *      TYP_CARTE (French Bank), TYP_HEALTH(French Health), TYP_EXPORT (Export)
 *    - mask : Key "F" 031 -> Parameters initialisation (0:absent, 1:present)
 *    - response_number : should be incremented
 * \return                                           
 *  FCT_OK
 * \header sdk30.h
 * \source entry.c 
*/
static int give_your_domain_ (NO_SEGMENT no, S_INITPARAMOUT *param_out)
{
	(void) no;

    /// Return application domain to Manager
	/// Setting parameters initialisation
	param_out->returned_state[param_out->response_number].mask = MSK_ALL;
    /// International domain
	param_out->returned_state[param_out->response_number].application_type = TYP_EXPORT;
	param_out->response_number++;

	return (FCT_OK);
}



//===========================================================================
//! \brief This function tests the presence of security DLL. And if it has
//! at least a release 0204.
//===========================================================================
static void	Test_DLL_Security_Presence(void)
{
	int sec_ver;
	int ret; 
	FILE * printer;

#ifndef _SIMULPC_
	ret = ObjectLoad (OBJECT_TYPE_DLL, "SECURITY");  
#else
	ret =0;
#endif 

	if ((ret != 0) && (ret != OL_ALREADY_LOADED))
	{
		printer=fopen("PRINTER","w-");
		if (printer)
		{
			pprintf ("\n""Custom \n");
			pprintf ("Please LOAD DLL SECURITY\n");

			pprintf ("\n\n\n\n\n");
			ttestall(PRINTER,0);
			fclose(printer);
		}
	}
	else
	{ 		
#ifndef _SIMULPC_
		sec_ver = SEC_Version();
#else
		sec_ver =0x020400;
#endif 

		if (sec_ver<0x020400)
		{
			printer=fopen("PRINTER","w-");
			if (printer)
			{
				pprintf ("\n""Custom \n");
				pprintf ("\n""Please LOAD DLL SECURITY\nWith VERSION >= 0204");

				pprintf ("\n\n\n\n\n");
				ttestall(PRINTER,0);
				fclose(printer);
			}
		}
	}
}



/** Display a message "TPASS DLL NOT LOADED"
 * \header sdk30.h
 * \source entry.c 
*/

static void Display_No_Dll_Msg (void)
{
	MSGinfos tMsg;
	int lg_code;

	// Get the manager language (merchant language)
	lg_code = PSQ_Give_Language();

	ClessSample_Term_Read_Message(STD_MESS_DLL_TPASS, lg_code, &tMsg);
	Helper_DisplayTextMerchant(ERASE, HELPERS_MERCHANT_LINE_2, &tMsg, NOLEDSOFF);
	ClessSample_Term_Read_Message(STD_MESS_NOT_LOADED, lg_code, &tMsg);
	Helper_DisplayTextMerchant(NO_ERASE, HELPERS_MERCHANT_LINE_3, &tMsg, NOLEDSOFF);

	Helper_RefreshScreen(WAIT, HELPERS_MERCHANT_SCREEN);
}



/** Initialise data and create disks, eventually ends interrupted transaction
 *  by returning S_TRANS_OUT.
 * \param    param_out (-O) Eventually ends interrupted transaction
 * \return                                           
 *  FCT_OK
 * \header sdk30.h
 * \source entry.c 
*/

static int after_reset_ (NO_SEGMENT no, S_TRANSOUT *param_out)
{
    unsigned char chgt;
	TYPE_CHGT  type;

	(void)param_out;

	g_bDllTpassLoaded = (TPasslib_open() == 0);	///< TPass DLL Library
	
	/// Reset management
	first_init(no, &chgt, (unsigned char *)&type);	///< New software loaded ?
	if (chgt==0xFF)									///< Yes, just loaded with first execution
	{ 
        raz_init(no);								///< Reset indicator downloading
	}
	
	// Try to restore parameters from sav file
	if (ClessSample_Parameters_RestoreParam (&pTreeCurrentParam) != 0)
	{
		GTL_Traces_TraceDebug("after_reset_ : ClessSample_Parameters_RestoreParam ko");
		
		// Read default parameters
		ClessSample_Parameters_ReadDefaultParameters(&pTreeDefaultParam);
		
		if (ClessSample_Parameters_SaveParam (pTreeDefaultParam) != 0)
		{
			GTL_Traces_TraceDebug("after_reset_ : ClessSample_Parameters_SaveParam ko");
		}
		else // Parameter has been correctly loaded/saved
		{
			ClessSample_Parameters_InitParameters(&pTreeCurrentParam);
			pTreeCurrentParam = pTreeDefaultParam; // Update pTreeCurrentParam for later use...
			pTreeDefaultParam = NULL;
		}
	}

	// Try to restore the Data Exchange file from the saved file
	if (ClessSample_DataExchange_RestoreFile (&pTreeCurrentDataExchange) != 0)
	{
		ClessSample_DataExchange_InitTlvTree (&pTreeCurrentDataExchange);
		pTreeCurrentDataExchange = NULL;
	}

	
	// Create or restore the batch
	ClessSample_Batch_Restore ();

	ClessSample_Disk_Open_MyDisk();

	// Try to load black list parameters if existing
	ClessSample_BlackListLoad();

	// Indicate CA checking has to be done
	gs_bCaKeyCheckingDone = FALSE;

	// Init the transaction sequence counter
	ClessSample_Batch_InitTransactionSeqCounter(FALSE);

	Test_DLL_Security_Presence();

	ClessSample_Term_Initialise();

	ClessSample_DumpData_InitOutput();

	if (g_bDllTpassLoaded)
	{
		// Set the LEDs into the idle state
		HelperLedsIdleState();
	}
	else
	{
		Display_No_Dll_Msg();
	}

	if (ClessSample_Unattended_IsUnattendedMechanism())
		ClessSample_Unattended_AfterReset (no);

	return FCT_OK;
}



/** Report application name to Manager.
 * \param    param_out (-O)
 *    - appname : Application name 
 *    - no : Application number
 *    - response_number : should be incremented
 * \return                                           
 *  FCT_OK
 * \header sdk30.h
 * \source entry.c 
*/

static int is_name_(NO_SEGMENT no, S_ETATOUT *param_out)
{
	strcpy(param_out->returned_state[param_out->response_number].appname, appName);
	param_out->returned_state[param_out->response_number].no_appli = no;
	param_out->response_number++;

	return (FCT_OK);
}



/** Report application state initialise or not to Manager.
 * \param    param_out (-O)
 *    - response : 
 *      REP_OK (Initialised), REP_KO (Not initialised)  
 * \return                                           
 *  FCT_OK
 * \header sdk30.h
 * \source entry.c 
*/

static int is_state_(NO_SEGMENT no, S_ETATOUT *param_out)
{
	int retour; 

	/// Return application state
	if (g_bDllTpassLoaded)
	{
		param_out->returned_state[param_out->response_number].state.response = REP_OK;
		retour = is_name_ (no, param_out);
		
		// Parameters control checking
		if (!gs_bCaKeyCheckingDone)
		{
			ClessSample_Parameters_CheckCaKeysCrc(pTreeCurrentParam);
			ClessSample_Parameters_CreateSupportedCertificateListForKernel (pTreeCurrentParam, DEFAULT_EP_KERNEL_PAYPASS);
			ClessSample_Parameters_BuildAIDNodes(pTreeCurrentParam);
			gs_bCaKeyCheckingDone = TRUE;
		}

		// Remove Application name on the header
		EventHeader (gs_nHeaderEventMask ^ _APPLI_STATE_);
	}
	else
	{
		param_out->returned_state[param_out->response_number].state.response = REP_KO;
		retour = is_name_ (no, param_out);
	}

	// Clean up the Torn Transaction log by removing torn records that were not recovered and that have been aged off the log.
	if (ClessSample_Menu_IsAutomaticCleanTornOn())
		if (ClessSample_Torn_IsRecoverySupported())
			ClessSample_Torn_CleanLog();

	return (retour);
}



/** Allows the application to display its idle message when Manager goes back 
 *  to idle (the application should have the higher priority).
 * \return                                           
 *  FCT_OK
 * \header sdk30.h
 * \source entry.c 
*/

static int idle_message_ (NO_SEGMENT no)
{
	FILE *hDisplay;
	int nFont;
	char idleMessage[256];

	(void) no;

	if (g_bDllTpassLoaded)
	{
		if (ClessSample_Unattended_IsUnattendedMechanism())
			if (ClessSample_Unattended_IsUnattendedTerminalWithDisplayWithUCMC ())
				iLIBUCM_Display_Graphic_Start(UCMC_DISPLAY);

		/// Idle message management
		hDisplay = fopen("DISPLAY","w");        ///< Open display driver.
		if (hDisplay)
		{
			nFont = GetDefaultFont();               ///< Retrieve default font
			
			CreateGraphics(_LARGE_);                ///< Create graphic font
			strcpy(idleMessage,appName);
			strcat(idleMessage, "\n");
			strcat(idleMessage,idleMsgPart1);
			strcat(idleMessage, "\n");
			strcat(idleMessage,idleMsgPart2);
			strcat(idleMessage, "\n");
			strcat(idleMessage,idleMsgPart3);
			strcat(idleMessage, "\n");
			_DrawString((char*) idleMessage,  0, 10, _OFF_);
			PaintGraphics();                        ///< Display idle message

			SetDefaultFont(nFont);                  ///< Restore default font
			fclose(hDisplay);	                    ///< Close display driver
		}

		if (ClessSample_Unattended_IsUnattendedMechanism())
			if (ClessSample_Unattended_IsUnattendedTerminalWithDisplayWithUCMC ())
				iLIBUCM_Display_Graphic_Stop(UCMC_DISPLAY);

		// Set the LEDs into the idle state
		HelperLedsIdleState();

		// Display specific messages for unattended environments, if applicable
		if (ClessSample_Unattended_IsUnattendedMechanism())
			ClessSample_Unattended_IdleMessage();
	}

	return FCT_OK;
}



/** It's activated when pressing on "F" key to select the right application 
 *  to go on menu.
 * \return                                           
 *  FCT_OK
 * \header sdk30.h
 * \source entry.c 
*/

static int more_function_ (NO_SEGMENT nAppliNum)
{
	(void) nAppliNum;

	if (ClessSample_Unattended_IsUnattendedMechanism())
		if (ClessSample_Unattended_IsUnattendedTerminalWithDisplayWithUCMC ())
			iLIBUCM_Display_Graphic_Start(UCMC_DISPLAY);

	if (g_bDllTpassLoaded)
		ClessSample_Menu_MainMenuDisplay();
	else Display_No_Dll_Msg();

	if (ClessSample_Unattended_IsUnattendedMechanism())
		if (ClessSample_Unattended_IsUnattendedTerminalWithDisplayWithUCMC ())
			iLIBUCM_Display_Graphic_Stop(UCMC_DISPLAY);
	
	return (FCT_OK);
}



/** It's activated when key is pressed and terminal is in idle mode. 
 * \param    key_in (I-)
 *    - keycode : Key pressed. 
 * \param    key_out (-O)
 *    - keycode : Key pressed, new key, 0=disable. 
 * \return                                           
 *  FCT_OK
 * \header sdk30.h
 * \source entry.c 
*/
static int keyboard_event_ (NO_SEGMENT noappli, S_KEY *key_in, S_KEY *key_out)
{
	int nOldStateHeader;

	(void) noappli;

	/// Keyboard management
	switch (key_in->keycode)
	{
	case N1: case N2:
		if (!ClessSample_Unattended_IsUnattendedMechanism())
		{
			nOldStateHeader = StateHeader(0);
		
			// Start the transaction
			ClessSample_ExplicitSelection_Process (key_in->keycode == N2);

			key_out->keycode = T_ANN;

			StateHeader(nOldStateHeader);
		}
		else
		{
			key_out->keycode = 0;               ///< Inhibit these keys to Manager for International domain
		}
		break;
	case N0: case N3: case N4: 
	case N5: case N6: case N7: case N8: case N9: 
	case T_VAL : case T_POINT : 
		key_out->keycode = 0;               ///< Inhibit these keys to Manager for International domain
		break;
	case T_ANN:
		if (!ClessSample_Menu_IsAutomaticCleanTornOn())
			if (ClessSample_Torn_IsRecoverySupported())
				ClessSample_Torn_CleanLog();
		key_out->keycode=key_in->keycode;
		break;
	case F2 : case F3 :
	case T_CORR : case NAVI_CLEAR : case NAVI_OK : 
	case F1: case F4: 
	case UP : case DOWN :
	case T_F :                              ///< do not filter F key and return the same key ! 
		key_out->keycode=key_in->keycode;   ///< Return the same key value for keys above ! 
		break; 
	default :
		key_out->keycode=key_in->keycode;
		break;
	}

	return (FCT_OK);
}



/** It's activated on "F" key: Consultation->State. 
 *  To print terminal content.  
 * \return                                           
 *  FCT_OK
 * \header sdk30.h
 * \source entry.c 
*/
static int state_ (NO_SEGMENT no)
{
	DATE date;
   	object_info_t infos;
	FILE     *hPrinter;
	
	/// Print application info
	ObjectGetInfo(OBJECT_TYPE_APPLI, no, &infos);       ///< Retrieve application info

	hPrinter=fopen( "PRINTER", "w-*" );                 ///< Open printer driver
	if (hPrinter!=NULL) 
	{	
		pprintf("\x1b""E%s\n""\x1b""F",appName);        ///< Print application name
		pprintf("         STATE         \n"
			    "Application used as\n"
			    "IngeDev Template\n\n");
		read_date(&date);                               ///< Print date and time
		pprintf(szDate, date.day, date.month, date.year, date.hour, date.minute);
		pprintf("File    : %s\n",infos.file_name);      ///< Print application file name
		pprintf("CRC     : %04x\n",infos.crc);          ///< Print application CRC
		ttestall(PRINTER, 0);	  

		fclose(hPrinter);                               ///< Close printer driver
	}
	
	return FCT_OK;
}



/** Do you need the peripherals at the next call of time_function()?.
 *  It's call every minute.
 * \param    param_out (-O)
 *    - response : 
 *      REP_OK (Manager closes all peripherals), REP_KO (Manager keeps all peripherals opened)  
 * \return                                           
 *  FCT_OK
 * \header sdk30.h
 * \source entry.c 
*/
static int is_time_function_ (NO_SEGMENT no, S_ETATOUT *param_out)
{
	int retour;

	/// Peripherals needed?
	param_out->returned_state[param_out->response_number].state.response=REP_OK;
	retour = is_name_ (no, param_out);

	return(FCT_OK);		 
}



/** It's activated on "F" key: Initialisation->Parameters->List.
 *  Each time Manager wants to change its own parameters.
 * \param    param_out (-O)
 *    - mask : Key "F" 031 -> Parameters modification (0:accepting, 1:refusing)
 * \return                                           
 *  FCT_OK
 * \header sdk30.h
 * \source entry.c 
*/
static int is_change_init_(NO_SEGMENT no, S_ETATOUT *param_out)
{
	S_ETATOUT etatout;
	int       retour;
	memcpy(&etatout, param_out, sizeof(etatout));

	/// accept all 
	etatout.returned_state[etatout.response_number].state.mask=0;
	memcpy(param_out,&etatout,sizeof(etatout));
	retour = is_name_ (no, param_out);
	return(FCT_OK);		 
}



/** It's activated each time Manager wants to run a downloading session (local or remote).
 *  "F" key: Evolution->Load->Local or Evolution->Remote Load
 * \param    param_out (-O)
 *    - response : 
 *      REP_OK (App authorises donwloading process), REP_KO (App refuses any downloading process)  
 * \return                                           
 *  FCT_OK
 * \header sdk30.h
 * \source entry.c 
*/
static int is_evol_pg_ (NO_SEGMENT no, S_ETATOUT *param_out)
{
	int retour;

    /// Downloading process allowed?
	param_out->returned_state[param_out->response_number].state.response=REP_OK;
	retour = is_name_ (no, param_out);

	return(FCT_OK);		 
}



/** It's activated each time Manager wants to delete an application.
 *  "F" key: Deletion
 * \param    param_out (-O)
 *    - response : 
 *      DEL_YES (App authorises deletion process), DEL_NO (App refuses any deletion process)  
 * \return                                           
 *  FCT_OK
 * \header sdk30.h
 * \source entry.c 
*/
static int is_delete_ (NO_SEGMENT no, S_DELETE *param_out)
{
	(void) no;

	/// Deletion process allowed?
	param_out->deleting=DEL_YES;

	return (FCT_OK);
}



/** Manager reports parameters file received from LLT.
 *  It's activated upon reception of a parameter file by the manager.
 * \param    param_in (I-)
 *    - volume_name : SYSTEM (File loaded in CFS), HOST (File loaded in DFS).
 *    - file_name : Application file name
 * \return                                           
 *  FCT_OK
 * \header sdk30.h
 * \source entry.c 
*/
static int file_received_ (NO_SEGMENT no, S_FILE *param_in)
{
	unsigned char * pSha;
	int nCRCLength;
	int nResult;
	int nIndex;
	char StrBuff[100];
	char TmpStr[10];
	
	(void) no;

	// Try to read parameter file and store it into an internal TLV tree structure
	nResult = ClessSample_Parameters_ReadXMLFile((char*)param_in->volume_name, (char*)param_in->file_name, &pTreeCurrentParam);
	if (nResult == STOP) // Inputed file is a parameter file 
	{
		// File has been received
		GTL_Traces_DiagnosticText ("CLESSCUST.PAR file received\n");
		
		// Prepare all the information (before the transaction) for each AID
		
		// Trace prepared data
		ClessSample_Parameters_Trace_Parameter_AID_Structure();
		
		// Compute the configuration CRC
		ClessSample_Parameters_Compute_Config_CRC(&pTreeCurrentParam, &nCRCLength, &pSha);
		{
			sprintf(StrBuff, "Parameters CRC : \n");
			
			for (nIndex=0; nIndex<nCRCLength; nIndex++)
			{
				sprintf(TmpStr, "%02x", pSha[nIndex]);
				strcat(StrBuff, TmpStr);
			}
		    GTL_Traces_TraceDebug("%s", StrBuff);
		}
		return (nResult);
	}

	// Check if the file was a Data Exchange file
	nResult = ClessSample_DataExchange_ReadXMLFile((char*)param_in->volume_name, (char*)param_in->file_name, &pTreeCurrentDataExchange);

	if (nResult == STOP) // Inputed file is a Data Exchange file 
	{
		///ClessSample_DumpData_DumpTlvTreeIndented (pTreeCurrentDataExchange, "DUMP MCW XML");
		GTL_Traces_DiagnosticText ("DEKDET.PAR file received\n");
		return (nResult);
	}

	// Try to read black List parameter
	nResult = ClessSample_BlackListGetNewFile(param_in->volume_name, param_in->file_name);
	if (nResult == STOP) // Inputed file is a Black list parameter file 
	{
		GTL_Traces_DiagnosticText ("CLESSBLACK.PAR file received\n");
		return (nResult);
	}
	
	return (nResult);
}



/** 
 *  It's activated when a card is inserted, swiped or manually entry.
 *  Ask the application if the card need a specific processing.
 * \param    param_out (-O)
 *    - response : 
 *      REP_OK (card processing), REP_KO (no card processing)  
 *  Only one application wants to process the card, manager calls CARD_INSIDE entry.
 *  More application wants to process the card, manager asks for card removal.
 *  If no application wants to process the card, manager goes on with selection process. 
 * \return                                           
 *  FCT_OK
 * \header sdk30.h
 * \source entry.c 
*/
static int is_card_specific_ (NO_SEGMENT no, S_TRANSIN *param_in, S_ETATOUT *param_out)
{
	int ret; 

	(void) param_in;

	/// Return application state
	param_out->returned_state[param_out->response_number].state.response = REP_KO;
	ret = is_name_ (no, param_out);
	
	return (FCT_OK);
}



/** 
 * Enable CGUI mode of the manager for this application.
 * \return   
 *  FCT_OK
 * \header sdk30.h
 * \source entry.c 
*/

static int give_your_specific_context_(const NO_SEGMENT AppliNum, S_SPECIFIC_CONTEXT* pParamOut)
{
	// Initialise the output parameter
	memset(&pParamOut->returned_state[pParamOut->response_number], 0,
		sizeof(pParamOut->returned_state[pParamOut->response_number]));

	strcpy(pParamOut->returned_state[pParamOut->response_number].appname, "844084----");
	pParamOut->returned_state[pParamOut->response_number].no_appli = AppliNum;
	pParamOut->returned_state[pParamOut->response_number].mask = 0;
	pParamOut->returned_state[pParamOut->response_number].type = 0;
	pParamOut->returned_state[pParamOut->response_number].support = 0;
	pParamOut->returned_state[pParamOut->response_number].cam = 0;

	// The application is CGUI compliant
	///pParamOut->returned_state[pParamOut->response_number].cgui = (CGUI_MASK);
	pParamOut->response_number++;

	return FCT_OK;
}



/** 
 * \brief Services registration and priority.  
 *  For all services except idle_message, priority => 0x00 highest and 0xFF lowest
 *  For idle_message, priority => 0x00 lowest 0xFF highest
 * \header sdk30.h
 * \source entry.c 
*/
static int give_interface_ (unsigned short AppliNum, void* pParamIn, void* pParamOut)
{
	int i;

	(void)pParamIn;
	(void)pParamOut;

	if (ClessSample_Unattended_IsUnattendedMechanism())
	{
		ClessSample_Unattended_InitTransactionStartData ();

		for(i = 0; i < (int)(sizeof(ServicesUnattended) / sizeof(ServicesUnattended[0])); i++)
			ServicesUnattended[i].appli_id = AppliNum;

		ServiceRegister((sizeof(ServicesUnattended) / sizeof(ServicesUnattended[0])), ServicesUnattended);

		// Security DLL open 
		SEClib_Open();
	}
	else
	{
		for(i = 0; i < (int)(sizeof(ServicesStandard) / sizeof(ServicesStandard[0])); i++)
			ServicesStandard[i].appli_id = AppliNum;

		ServiceRegister((sizeof(ServicesStandard) / sizeof(ServicesStandard[0])), ServicesStandard);

		// Security DLL open 
		SEClib_Open();
	}

	return FCT_OK;
}



/** 
 * \brief This service is called by the contactless kernels for customisation processing.
 * This is the application that provide kernel the service and the application type to call for customisation. 
 * \param[in] nSize Size of \a pData (not used as \a pData is a shared service call struct).
 * \param[in,out] pData Data buffer to be used to get and provide data to the kernel.  
 * \return   
 *  	- \ref FCT_OK always.
 */
static int custom_kernel_ (unsigned int nSize, void * pData)
{
	int nResult;
	T_SERVICE_CALL_SHARED_EXCHANGE_STRUCT * pSharedStruct;

	(void) nSize;
	
	pSharedStruct = (T_SERVICE_CALL_SHARED_EXCHANGE_STRUCT *)pData;

	// Call the customisation depending on the kernel used
    nResult = ClessSample_Customisation_Process (pSharedStruct->pDataStruct);
    
	return (nResult);
}



/** 
 * \brief This service is called by the contactless paypass kernel for Data Exchange processing.
 * The the application provides the kernel with the service and the application type to call for customisation. 
 * \param[in] nSize Size of \a pData (not used as \a pData is a shared service call struct).
 * \param[in,out] pData Data buffer to be used to get and provide data to the kernel.  
 * \return   
 *  	- \ref FCT_OK always.
 */

static int de_kernel_ (unsigned int nSize, void * pData)
{
	int nResult;
	T_SERVICE_CALL_SHARED_EXCHANGE_STRUCT * pSharedStruct;

	(void) nSize;
	
	pSharedStruct = (T_SERVICE_CALL_SHARED_EXCHANGE_STRUCT *)pData;

	// Call the customisation depending on the kernel used
    nResult = ClessSample_Customisation_Data_Exchange (pSharedStruct->pDataStruct);
    
	return (nResult);
}



/** Inter application messaging.
 *  It's activated each time Manager received a message in its mailbox for this application.
 * \param    param_in (I-)
 *    - sender : Sender ID.
 *    - receiver : Receiver ID.
 *    - type : IAM type.
 *    - length : Message length.
 *    - value : Message received.
 * \return                                           
 *  FCT_OK
 * \header sdk30.h
 * \source entry.c 
*/
static int message_received_(NO_SEGMENT AppliNum, S_MESSAGE_IAM* pParamIn)
{	
	(void)AppliNum;
	(void)pParamIn;
	FILE * hDisplay;

	ClessSample_ComEventSetSerialRequest();
	
    hDisplay = fopen("DISPLAY","w");


	if (pParamIn->type == 4) /* Msg from EMV Custom */
	{
        GTL_Traces_TraceDebug("msg type = 4 received");
		ClessSample_Unattended_PrintDump((char *)pParamIn->value);
	}
	else if (pParamIn->type == COM_EVT_COMMUNICATION_ORDER) /* Msg from rs232 */
	{
		ClessSample_Unattended_ExecuteCommand (pParamIn->length, (char*)pParamIn->value);
	}
	else if (pParamIn->type == COM_EVT_START_ORDER)
	{
		GTL_Traces_TraceDebug("COM_EVT_START_ORDER");
    	ClessSample_Comevent_Manage (DO_OPEN); /* return allways FCT_OK fct */
	}
	else if (pParamIn->type == COM_EVT_STOP_ORDER)
	{
		GTL_Traces_TraceDebug("COM_EVT_STOP_ORDER");
    	ClessSample_Comevent_Manage (DO_CLOSE); /* return allways FCT_OK fct */
	}
	
	if (hDisplay)
		fclose(hDisplay);

	ClessSample_ComEventUnSetSerialRequest();
    
	return (FCT_OK);
}



/** 
 * \brief This service is called by the contactless kernels for customisation processing.
 * This is the application that provide kernel the service and the application type to call for customisation. 
 * \param[in] nSize Size of \a pData (not used as \a pData is a shared service call struct).
 * \param[in,out] pData Data structure containing the service data to be used.  
 * \return The service returned code.
 */
static int Main_(unsigned int nSize, StructPt* pData)
{
	NO_SEGMENT AppliNum;
	int nResult;

	(void)nSize;

	AppliNum = (NO_SEGMENT)ApplicationGetCurrent();
	switch(pData->service)
	{
	case AFTER_RESET:
		nResult = after_reset_(AppliNum, &pData->Param.AfterReset.param_out);
		break;
	case IS_DELETE:
		nResult = is_delete_(AppliNum, &pData->Param.IsDelete.param_out);
		break;
	case IS_NAME:
		nResult = is_name_(AppliNum, &pData->Param.IsName.param_out);
		break;
	case IS_STATE:
		nResult = is_state_(AppliNum, &pData->Param.IsState.param_out);
		break;
	case FILE_RECEIVED:
		nResult = file_received_(AppliNum, &pData->Param.FileReceived.param_in);
		break;
	case GIVE_YOUR_DOMAIN:
		nResult = give_your_domain_(AppliNum, &pData->Param.GiveYourType.param_out);
		break;
	case GIVE_MONEY_EXTENDED:
		nResult = give_money_extended_(AppliNum, NULL, &pData->Param.GiveMoneyExtended.param_out);
		break;
	case MORE_FUNCTION:
		nResult = more_function_(AppliNum);
		break;
	case IS_CARD_SPECIFIC:
		nResult = is_card_specific_(AppliNum, &pData->Param.ClessIsSpecific.param_in, &pData->Param.ClessIsSpecific.param_out);
		break;
	case IS_CHANGE_INIT:
		nResult = is_change_init_(AppliNum, &pData->Param.IsChangeInit.param_out);
		break;
	case IS_EVOL_PG:
		nResult = is_evol_pg_ (AppliNum, &pData->Param.IsEvolPg.param_out);
		break;
	case IS_TIME_FUNCTION:
		nResult = is_time_function_(AppliNum, &pData->Param.IsTimeFunction.param_out);
		break;
	case STATE:
		nResult = state_(AppliNum);
		break;
	case IDLE_MESSAGE:
		nResult = idle_message_(AppliNum);
		break;
	case SELECT_FUNCTION_EMV:
		nResult = select_function_emv_(AppliNum,&pData->Param.SelectFunctionEmv.param_in,&pData->Param.SelectFunctionEmv.param_out);
		break;
	case GIVE_YOUR_SPECIFIC_CONTEXT:
		nResult = give_your_specific_context_(AppliNum, &pData->Param.GiveYourSpecificContext.param_out);
		break;
	case KEYBOARD_EVENT:
		nResult = keyboard_event_(AppliNum, &pData->Param.KeyboardEvent.param_in, &pData->Param.KeyboardEvent.param_out);
		break;
	case COM_EVENT:
		nResult = ClessSample_Comevent_Event(AppliNum, &pData->Param.ComEvent.param_in, &pData->Param.ComEvent.param_out);
		break;
	case MESSAGE_RECEIVED:
		nResult = message_received_(AppliNum, &pData->Param.MessageReceived.param_in);
		break;
	default:
		nResult = FCT_OK;
		break;
	}

	return nResult;
}



#ifdef __cplusplus
extern "C" {
#endif

/** entry() is called by the OS for recording services and opening DLL(s).                   
 *  The RegisteryPowerFailure() can also be moved to entry().
 * \header sdk30.h
 * \source entry.c 
*/
void entry(void)
{
	object_info_t info;
	
	gs_nHeaderEventMask = EventHeader (0); // To get the initial Header Event Mask and to set the current to 0
	EventHeader (gs_nHeaderEventMask); // Restore the Header Event mask

	/// Recording services
	ObjectGetInfo(OBJECT_TYPE_APPLI, ApplicationGetCurrent(),&info);
	give_interface_(info.application_type, NULL, NULL);
	
	//memcpy(appName,info.name,OBJECT_NAME_LEN);
	//appName[OBJECT_NAME_LEN] = '\0';
}

#ifdef __cplusplus
}
#endif
