# Manual card entry
                                  
app.SendKeys('1')                                      # recorded
app.Sleep(1)                                          # recorded
app.SendKeys('2')                                      # recorded
app.Sleep(1)                                          # recorded
app.SendKeys('3')
app.Sleep(1)                                          # recorded
app.SendKeys('4')
app.Sleep(1)                                          # recorded
app.SendKeys('{ENTER}') 
app.Sleep(1)
app.SendKeys('F')  
app.Sleep(1)
app.SendKeys('4')  
app.Sleep(1)
app.SendKeys('0')  
app.Sleep(1)
app.SendKeys('2')  
app.Sleep(1)
app.SendKeys('8')  
app.Sleep(2)
app.SendKeys('9')  
app.Sleep(1)
app.SendKeys('2')  
app.Sleep(1)
app.SendKeys('0')  
app.Sleep(1)
app.SendKeys('0')  
app.Sleep(1)
app.SendKeys('0')  
app.Sleep(1)
app.SendKeys('2')  
app.Sleep(1)
app.SendKeys('4')  
app.Sleep(1)
app.SendKeys('6')  
app.Sleep(1)
app.SendKeys('5')  
app.Sleep(1)
app.SendKeys('6')  
app.Sleep(1)
app.SendKeys('5')  
app.Sleep(1)
app.SendKeys('6')  
app.Sleep(1)
app.SendKeys('{ENTER}')   
app.Sleep(1)
app.SendKeys('1')  
app.Sleep(1)
app.SendKeys('1')  
app.Sleep(1)
app.SendKeys('1')  
app.Sleep(1)
app.SendKeys('3')  
app.Sleep(1)
app.SendKeys('{ENTER}') 
