
app.SendKeys('F')
app.SendKeys('{DOWN}')
app.Sleep(1)
app.SendKeys('{ENTER}')
app.SendKeys('1')
app.SendKeys('2')
app.SendKeys('3')
app.SendKeys('4')
app.SendKeys('{ENTER}')
app.Sleep(1)
app.SendKeys('{DOWN}')
app.Sleep(1)
app.SendKeys('{ENTER}')
app.Sleep(1)
app.SendKeys('{DOWN}')
app.SendKeys('{DOWN}')
app.SendKeys('{DOWN}')
app.SendKeys('{ENTER}')
app.Sleep(1)
app.SendKeys('{ENTER}')
app.Sleep(1)
app.InsertCard()
app.Sleep(2)
app.RemoveCard()

