app.SendKeys('F')
app.Sleep(1)
app.SendKeys('{DOWN}')
app.Sleep(1)
app.SendKeys('{ENTER}')
app.SendKeys('1')
app.SendKeys('2')
app.SendKeys('3')
app.SendKeys('4')
app.SendKeys('{ENTER}')
app.Sleep(1)
app.SendKeys('{ENTER}')
app.Sleep(1)
app.SendKeys('{DOWN}')
app.Sleep(1)
app.SendKeys('{ENTER}')

