\connect oegw oe

ALTER TABLE OEGW_CLIENT ADD COLUMN EFFECT_DATE TIMESTAMP;

ALTER TABLE OEGW_SESSION ADD COLUMN SENT INT;
ALTER TABLE OEGW_SESSION ADD COLUMN GETS INT;
ALTER TABLE OEGW_SESSION ADD COLUMN POSTS INT;
ALTER TABLE OEGW_SESSION ADD COLUMN GETS_RECEIVED INT;
ALTER TABLE OEGW_SESSION ADD COLUMN GETS_SENT INT;
ALTER TABLE OEGW_SESSION ADD COLUMN POSTS_RECEIVED INT;
ALTER TABLE OEGW_SESSION ADD COLUMN POSTS_SENT INT;
ALTER TABLE OEGW_SESSION ADD COLUMN FRMW_RECEIVED INT;
ALTER TABLE OEGW_SESSION ADD COLUMN FRMW_SENT INT;

ALTER TABLE OEGW_SRV ADD COLUMN HASH_CHECK BOOLEAN DEFAULT false;
ALTER TABLE OEGW_SRVSUBSCR ADD COLUMN INHERITED BOOLEAN DEFAULT false;
ALTER TABLE OEGW_SRVSUBSCR ADD COLUMN PREVIOUS_ITID VARCHAR(32) DEFAULT NULL;

CREATE TABLE OEGW_SRVSUBSCR_HISTORY
(
   ID bigint NOT NULL,
   SRVID VARCHAR(255) NOT NULL,
   STATUS CHAR(1) NOT NULL,
   TERM_ITID VARCHAR(32) NOT NULL,
   CONTRACT VARCHAR(255) NOT NULL,
   STATUS_DATE TIMESTAMP NOT NULL
);
CREATE SEQUENCE OEGWSRVSUBSCRHIST_SEQ
        INCREMENT BY 1 START WITH 1 NO MAXVALUE
        OWNED BY OEGW_SRVSUBSCR_HISTORY.ID;
ALTER TABLE OEGW_SRVSUBSCR_HISTORY
        ALTER COLUMN ID SET DEFAULT NEXTVAL('OEGWSRVSUBSCRHIST_SEQ');
        
ALTER TABLE OEGW_SRVSUBSCR_HISTORY 
        ADD CONSTRAINT OEGW_SRVSUBSCR_HISTORY_pkey PRIMARY KEY (id);


CREATE INDEX OEGW_TXN_TXNID ON OEGW_TXN(TXN_ID);


ALTER TABLE OEGW_TXN_MSG RENAME COLUMN TXN_ID TO TXN_DB_ID;

ALTER TABLE OEGW_TXN_MSG
        DROP CONSTRAINT OEGW_TXN_MSG_OEGW_TXN_FK;

ALTER TABLE OEGW_TXN_MSG
        ADD CONSTRAINT OEGW_TXN_MSG_OEGW_TXN_FK
                FOREIGN KEY (TXN_DB_ID) REFERENCES OEGW_TXN (ID);

DROP INDEX OEGW_TXN_TXN_ID;
CREATE INDEX OEGW_TXN_TXN_ID ON OEGW_TXN_MSG(TXN_DB_ID);


ALTER TABLE OEGW_RECONCILIATION_TXN
        ALTER COLUMN ID SET DEFAULT NEXTVAL('OEGWRECONCILIATION_SEQ');


CREATE TABLE OEGW_TERMRESERVE (
   ID                   BIGINT        NOT NULL PRIMARY KEY,
   ITID                 VARCHAR(255)  NOT NULL ,
   LOCKED               BOOLEAN       NOT NULL
);


CREATE TABLE OEGW_HASH (
   ID                   BIGINT        NOT NULL PRIMARY KEY,
   SRVID                VARCHAR(255)  NOT NULL ,
   RESOURCE             VARCHAR(255)  NOT NULL ,
   HASH                 VARCHAR(255)  NOT NULL
);

CREATE SEQUENCE OEGWHASH_SEQ
        INCREMENT BY 1 START WITH 1 NO MAXVALUE
        OWNED BY OEGW_HASH.ID;
ALTER TABLE OEGW_HASH
        ALTER COLUMN ID SET DEFAULT NEXTVAL('OEGWHASH_SEQ');

CREATE INDEX OEGW_HASH_SRVID ON OEGW_HASH(SRVID);
CREATE INDEX OEGW_HASH_RESOURCE ON OEGW_HASH(RESOURCE);
CREATE INDEX OEGW_HASH_HASH ON OEGW_HASH(HASH);
COMMENT ON COLUMN OEGW_HASH.SRVID IS 'Service id.';
COMMENT ON COLUMN OEGW_HASH.RESOURCE IS 'Resource.';
COMMENT ON COLUMN OEGW_HASH.HASH IS 'Resource hash.';


DELETE FROM WEB_SRVFIELD WHERE FIELD_NAME='BASE_URI';

DELETE FROM OEGW_DB_VERSION;

INSERT INTO OEGW_DB_VERSION
        (MAIN, MAJOR, MINOR, BUILD)
        VALUES (3,0,1,'0');