\connect oegw oe

ALTER TABLE OEGW_SESSION ALTER COLUMN ID DROP DEFAULT;
DROP SEQUENCE IF EXISTS OEGWSESSION_SEQ;
CREATE SEQUENCE OEGWSESSION_SEQ
        INCREMENT BY 1 START WITH 1 NO MAXVALUE
        OWNED BY OEGW_SESSION.ID;
ALTER TABLE OEGW_SESSION
        ALTER COLUMN ID SET DEFAULT NEXTVAL('OEGWSESSION_SEQ');
SELECT SETVAL('OEGWSESSION_SEQ', max(ID)) FROM OEGW_SESSION;

ALTER TABLE OEGW_TERMRESERVE ALTER COLUMN ID DROP DEFAULT;
DROP SEQUENCE IF EXISTS OEGWTERMRESERVE_SEQ;
CREATE SEQUENCE OEGWTERMRESERVE_SEQ
        INCREMENT BY 1 START WITH 1 NO MAXVALUE
        OWNED BY OEGW_TERMRESERVE.ID;
ALTER TABLE OEGW_TERMRESERVE
        ALTER COLUMN ID SET DEFAULT NEXTVAL('OEGWTERMRESERVE_SEQ');
SELECT SETVAL('OEGWTERMRESERVE_SEQ', max(ID)) FROM OEGW_TERMRESERVE;

ALTER TABLE CFGSRV_TTLS ALTER COLUMN PAN TYPE VARCHAR(38);

ALTER TABLE OEGW_CLIENT ADD COLUMN MODEL                VARCHAR(32)  NOT NULL DEFAULT 'other';
ALTER TABLE OEGW_CLIENT ADD COLUMN BROWSER              VARCHAR(32)  NOT NULL DEFAULT 'v31';
ALTER TABLE OEGW_CLIENT ADD COLUMN SCREENTYPE           VARCHAR(32)  NOT NULL DEFAULT 'uc32color';
ALTER TABLE OEGW_CLIENT ADD COLUMN RESOLUTION           VARCHAR(32);
ALTER TABLE OEGW_CLIENT ADD COLUMN MAGCARD              BOOLEAN  NOT NULL DEFAULT true;
ALTER TABLE OEGW_CLIENT ADD COLUMN ICCEMV               BOOLEAN  NOT NULL DEFAULT true;
ALTER TABLE OEGW_CLIENT ADD COLUMN CLESS                BOOLEAN  NOT NULL DEFAULT false;
ALTER TABLE OEGW_CLIENT ADD COLUMN PINPAD               BOOLEAN  NOT NULL DEFAULT false;
ALTER TABLE OEGW_CLIENT ADD COLUMN TOUCH                BOOLEAN  NOT NULL DEFAULT false;
ALTER TABLE OEGW_CLIENT ADD COLUMN PRINTER              BOOLEAN  NOT NULL DEFAULT true;

DELETE FROM OEGW_DB_VERSION;

INSERT INTO OEGW_DB_VERSION
        (MAIN, MAJOR, MINOR, BUILD)
        VALUES (3,1,0,'0');