\connect oegw oe

DROP INDEX IF EXISTS OEGW_SESSION_ENDDATE;
CREATE INDEX OEGW_SESSION_ENDDATE ON OEGW_SESSION USING BTREE(ENDDATE); 

ALTER TABLE OEGW_SRV ADD COLUMN ICON BIGINT;
ALTER TABLE OEGW_SRV ADD COLUMN PRIORITY INT DEFAULT 50;

ALTER TABLE OEGW_CLIENT ADD COLUMN IDLE VARCHAR(255);
ALTER TABLE OEGW_CLIENT ADD COLUMN CLIENTID_EXT INT;


CREATE TABLE OEGW_RESOURCE (
  ID BIGINT NOT NULL PRIMARY KEY,
  DATA TEXT NOT NULL,
  HASH VARCHAR(32) NOT NULL,
  NAME VARCHAR(255) NOT NULL
);
DROP SEQUENCE IF EXISTS OEGWRESOURCE_SEQ;
CREATE SEQUENCE OEGWRESOURCE_SEQ
        INCREMENT BY 1 START WITH 1 NO MAXVALUE
        OWNED BY OEGW_RESOURCE.ID;
ALTER TABLE OEGW_RESOURCE
        ALTER COLUMN ID SET DEFAULT NEXTVAL('OEGWRESOURCE_SEQ');

CREATE INDEX OEGW_RESOURCE_HASH ON OEGW_RESOURCE(HASH);


CREATE TABLE OEGW_SRVICON
(
   ID                   BIGINT          NOT NULL,--SERIAL WITH EXPLICIT SEQUENCE
   SRVID                BIGINT	        NOT NULL,  
   DATA1                TEXT            NOT NULL,
   DATA1_VERSION        BIGINT          NOT NULL,
   

   FOREIGN KEY (SRVID)
       REFERENCES OEGW_SRV(ID)
);
DROP SEQUENCE IF EXISTS OEGWSRVICON_SEQ;
CREATE SEQUENCE OEGWSRVICON_SEQ
        INCREMENT BY 1 START WITH 1 NO MAXVALUE
        OWNED BY OEGW_SRVICON.ID;
ALTER TABLE OEGW_SRVICON
        ALTER COLUMN ID SET DEFAULT NEXTVAL('OEGWSRVICON_SEQ');

ALTER TABLE OEGW_SRVICON
        ADD CONSTRAINT OEGW_SRVICON_PK
                PRIMARY KEY (ID);

ALTER TABLE OEGW_SRVICON
        ADD CONSTRAINT OEGW_SRV_FK
                FOREIGN KEY (SRVID) REFERENCES OEGW_SRV(ID);


CREATE TABLE OEGW_CLIENT_HISTORY (
  ID                    BIGINT          NOT NULL PRIMARY KEY,
  ITID                  VARCHAR(32)     NOT NULL,
  CLIENTID_EXT          INT,
  STATUS                VARCHAR(1)      NOT NULL,
  STATUS_DATE           TIMESTAMP
);

DROP SEQUENCE IF EXISTS OEGWCLIENTHISTORY_SEQ;
CREATE SEQUENCE OEGWCLIENTHISTORY_SEQ
        INCREMENT BY 1 START WITH 1 NO MAXVALUE
        OWNED BY OEGW_CLIENT_HISTORY.ID;

ALTER TABLE OEGW_CLIENT_HISTORY
ALTER COLUMN ID SET DEFAULT NEXTVAL('OEGWCLIENTHISTORY_SEQ');

CREATE INDEX OEGW_CLIENT_HISTORY_ITID ON OEGW_CLIENT_HISTORY(ITID);
CREATE INDEX OEGW_CLIENT_HISTORY_EXTERNAL_ID ON OEGW_CLIENT_HISTORY(CLIENTID_EXT);


DELETE FROM OEGW_DB_VERSION;

INSERT INTO OEGW_DB_VERSION
        (MAIN, MAJOR, MINOR, BUILD)
        VALUES (3,1,5,'0');