\connect oegw oe

ALTER TABLE OEGW_SESSION ALTER COLUMN ID DROP DEFAULT;
DROP SEQUENCE IF EXISTS OEGWSESSION_SEQ;
ALTER TABLE OEGW_TERMRESERVE ALTER COLUMN ID DROP DEFAULT;
DROP SEQUENCE IF EXISTS OEGWTERMRESERVE_SEQ;

ALTER TABLE OEGW_CLIENT DROP COLUMN MODEL;
ALTER TABLE OEGW_CLIENT DROP COLUMN BROWSER;
ALTER TABLE OEGW_CLIENT DROP COLUMN SCREENTYPE;
ALTER TABLE OEGW_CLIENT DROP COLUMN RESOLUTION;
ALTER TABLE OEGW_CLIENT DROP COLUMN MAGCARD;
ALTER TABLE OEGW_CLIENT DROP COLUMN ICCEMV;
ALTER TABLE OEGW_CLIENT DROP COLUMN CLESS;
ALTER TABLE OEGW_CLIENT DROP COLUMN PINPAD;
ALTER TABLE OEGW_CLIENT DROP COLUMN TOUCH;
ALTER TABLE OEGW_CLIENT DROP COLUMN PRINTER;

ALTER TABLE CFGSRV_TTLS ALTER COLUMN PAN TYPE VARCHAR(19);

DELETE FROM OEGW_DB_VERSION WHERE MAIN=3 AND MAJOR=1 AND MINOR=0;

INSERT INTO OEGW_DB_VERSION
        (MAIN, MAJOR, MINOR, BUILD)
        VALUES (3,0,2,'0');