\connect oegw oe

ALTER TABLE OEGW_SRV DROP COLUMN ICON;
ALTER TABLE OEGW_SRV DROP COLUMN PRIORITY;
ALTER TABLE OEGW_CLIENT DROP COLUMN IDLE;
ALTER TABLE OEGW_CLIENT DROP COLUMN CLIENTID_EXT;


DROP TABLE IF EXISTS OEGW_RESOURCE;

ALTER TABLE OEGW_SRVICON ALTER COLUMN ID DROP DEFAULT;
DROP SEQUENCE IF EXISTS OEGWSRVICON_SEQ;
DROP TABLE IF EXISTS OEGW_SRVICON;

ALTER TABLE OEGW_CLIENT_HISTORY ALTER COLUMN ID DROP DEFAULT;
DROP SEQUENCE IF EXISTS OEGWCLIENTHISTORY_SEQ;
DROP TABLE IF EXISTS OEGW_CLIENT_HISTORY;

DELETE FROM OEGW_DB_VERSION WHERE MAIN=3 AND MAJOR=2 AND MINOR=0;

INSERT INTO OEGW_DB_VERSION
        (MAIN, MAJOR, MINOR, BUILD)
        VALUES (3,1,0,'0');