// #LANGUAGE FR
// #FONFILE /LOCAL/MANAGER.SGN
// #MSGCODING ISO8859
// #FILETYPE 2
// #APPLITYPE 14
#message 0 MODEM_SETUP "Reglages Modem"
#message 1 MODEM_OUTPUT_LEVEL "Niveau d'emission"
#message 2 MODEM_DTMF_TIMING "DTMF"
#message 3 MODEM_ADVANCED_SETTINGS "Reglages Avances"
#message 4 MODEM_PRINT "Imprimer"
#message 5 MODEM_SAVE "Sauvegarder"
#message 6 MODEM_QUIT "Quitter"
#message 7 MODEM_LINE_TYPE "Type de ligne"
#message 8 MODEM_LINE_TYPE_LONG "Ligne longue"
#message 9 MODEM_LINE_TYPE_SHORT "Ligne courte"
#message 10 VALUE_BETWEEN_5_AND_30 "Valeur [5..30]"
#message 11 MODEM_MILLISECOND "Millisecondes"
#message 12 MODEM_STANDARD_RULE "Regle Standard"
#message 13 MODEM_BELOW_RULE "Regle Basse"
#message 14 MODEM_ABOVE_RULE "Regle Haute"
#message 15 BINARY_VALUE "Valeur Binaire"
#message 16 MODEM_DEFAULT_SETUP "Conf. par defaut"
#message 17 MODEM_RELOAD "Recharge Conf."
#message 18 HARDWARE_SETUP "Conf. Materielle"
#message 19 ETHERNET_SETUP "Conf. Ethernet"
#message 20 ETHERNET_IP_ADDR "Adresse IP"
#message 21 ETHERNET_NET_MASK "Masque de reseau"
#message 22 ETHERNET_GATEWAY "Passerelle"
#message 23 ETHERNET_BOOT_PROTO "Boot Proto"
#message 24 ETHERNET_PRINT "Imprimer"
#message 25 ETHERNET_SAVE "Sauvegarder"
#message 26 ETHERNET_QUIT "Quitter"
#message 27 ETHERNET_RELOAD "Recharge Conf."
#message 28 ETHERNET_STATIC "IP Fixe"
#message 29 ETHERNET_DHCP "DHCP"
#message 30 ETHERNET_BOOTP "BOOTP"
#message 31 MODEM_V22BIS_FORCED "Vitesse reduite"
#message 32 MODEM_CALIBRATION "Calibration"
#message 33 MODEM_SITE_CALIBRATION "Calibration Site"
#message 34 MODEM_TRY_CALIBRATION "Essaie "
#message 35 MODEM_PLEASE_WAIT "Patientez SVP"
#message 36 MODEM_STARTUP_KO "Init. KO"
#message 37 MODEM_START_CALIBRATION "Demarre Calibration"
#message 38 MODEM_KILL_CALIBRATION_FILE "Efface Fichier"
#message 39 MODEM_PRINT_CALIBRATION_FILE "Imprime Fichier"
#message 40 MODEM_CALIBRATION_CHANGE_PAD_NUMBER "Change Num PAD"
#message 41 BATTERY_SETUP "Conf. Batterie"
#message 42 NEW_BATTERY "Chang. Bat."
#message 43 SAVE_QUESTION "Sauvegarder ?"
#message 44 ANSWER_YES "Oui"
#message 45 ANSWER_NO "Non"
#message 46 DISCHARGE "Decharge"
#message 47 NEW_BATTERY_QUESTION "Nouvelle Batterie ?"
#message 48 FULL_DISCHARGE_QUESTION "Decharge profonde ?"
#message 49 DISCHARGING "Decharge" " en cours"
#message 50 BATTERY_LEVEL "Niveau Batterie"
#message 51 ETHERNET_DNS_1 "DNS 1"
#message 52 ETHERNET_DNS_2 "DNS 2"
#message 53 BACK_LIGHT "Retro-eclairage"
#message 54 BRIGHTER "Plus"
#message 55 DIMMER "Moins"
#message 56 ETHERNET_RESET_CONF "Reset Conf."
#message 57 START_ON_TILT "Tilt"
#message 58 USB_CHARGING "Charge USB"
#message 59 RETROFIT_MASV2 "Retrofit MASv2"
#message 60 RETROFIT_BLUETOOTH "Retrofit BlueTooth"
#message 61 BLUETOOTH_DRIVER_NOT_FOUND "Driver BlueTooth" "\n" " absent"
#message 62 GPRS_DRIVER_NOT_FOUND "Driver GPRS" "\n" " absent"
#message 63 GPRS_RETROFIT_BUSY "Retrofit GPRS" "\n" " Occupé"
#message 64 GPRS_RETROFIT_NOT_IMPLEMENTED "Retrofit GPRS" "\n" " non Disponible"
#message 65 BLUETOOTH_RETROFIT_NOT_IMPLEMENTED "BlueTooth non" "\n" " retrofitable"
#message 66 APPLICATION_NAME "Configuration"
#message 67 PLUS_ETHERNET "+Ethernet"
#message 68 PLUS_BATTERY "+Batterie"
#message 69 PLUS_BLUETOOTH "+Bluetooth"
#message 70 PLUS_GPRS "+GPRS"
#message 71 NO_MODEM_OPTION "Pas d'option modem"
#message 72 PLUS_MODEM "+Modem"
#message 73 MODEM_NUMBER_OF_DAYS "Nombre de jours"
#message 74 MODEM_NUMBER_OF_FAILURES "Nombre d'echecs"
#message 75 MODEM_LOOKUP_DEPTH "Profondeur"
#message 76 BLUETOOTH_SETUP "Reglages Socles"
#message 77 BLUETOOTH_ASSOCIATION "Association"
#message 78 BLUETOOTH_ADVANCED "Avances"
#message 79 BLUETOOTH_EXPERT "Experts"
#message 80 BLUETOOTH_ASSOCIATION_NOT_IMPLEMENTED "Association" "\n" "non disponible"
#message 81 BLUETOOTH_NEW_BASE "Nouveau Socle"
#message 82 BLUETOOTH_SELECT_BASE "Choix du Socle"
#message 83 BLUETOOTH_REMOVE_BASE "Supprime Socle"
#message 84 IN_PROGRESS "En cours ..."
#message 85 BLUETOOTH_ASSOCIATION_SUCCESS "Association OK"
#message 86 BLUETOOTH_ASSOCIATION_FAILURE "Association impossible"
#message 87 BLUETOOTH_PRINT_BASES "Imprime Socles"
#message 88 BLUETOOTH_NO_BASE "Aucun socle connu"
#message 89 USER_ABORT "Arret Utilisateur"
#message 90 NOT_ON_CRADLE "Pas sur socle"
#message 91 PRINTER_NOT_SUPPORTED "Non Supporte"
#message 92 PRINTER_NOT_AVAILABLE "Imprimante Indisponible"
#message 93 BATTERY_NOT_AVAILABLE "Pas de batterie"
#message 94 BATTERY_NOT_COMPATIBLE "Batterie Incompatible"
#message 95 BACK_ON_BASE "Retour Socle"
#message 96 WRONG_BT_DRIVER "Drivers Incompatibles"
#message 97 WRONG_BASE_FIRMWARE "Firmware Base KO"
#message 98 WRONG_PORTABLE_FIRMWARE "Firmware Portable KO"
#message 99 WRONG_FIRMWARES "Firmwares KO"
#message 100 MODEM_CURRENT_LIMITING "Limite de courant"
#message 101 ETHERNET_SPEED "Debit"
#message 102 ETHERNET_PING_IP_ADDRESS "Ping"
#message 103 ETHERNET_RECEIVED "Recus"
#message 104 ETHERNET_WAITING_RESPONSE "Attente Reponse..."
#message 105 BASE_UPDATE "Mise a jour Base"
#message 106 EXCHANGE_THIS_BASE "Ce Socle (IR)"
#message 107 EXCHANGE_STATUS_IDLE "Inactif"
#message 108 EXCHANGE_STATUS_CONNECTING "Connexion"
#message 109 EXCHANGE_STATUS_CONNECTED "Connecte"
#message 110 EXCHANGE_STATUS_SENDING "Envoi"
#message 111 EXCHANGE_STATUS_RECEIVING "Reception"
#message 112 EXCHANGE_STATUS_ACTIVATING "Activation"
#message 113 EXCHANGE_STATUS_DISCONNECTING "Deconnexion"
#message 114 EXCHANGE_CURRENT "Courant"
#message 115 BLUETOOTH_BASE_STATE "Etat Socle"
#message 116 BACKLIGHT_ON_BASE "Retroeclairage sur socle"
#message 117 BACKLIGHT_OUT_OF_BASE "Retroeclairage hors socle"
#message 118 DISPLAY_CONTRAST "Contraste"
#message 119 DISPLAY "Affichage"
#message 120 NEED_RESTART1 "Un redemarrage est"
#message 121 NEED_RESTART2 "requis ..."
#message 122 WIFI_SETUP_MESSAGE "Conf. Wifi"
#message 123 WIFI_PROFILE_MESSAGE "Profils"
#message 124 WIFI_INFO_MESSAGE "Infos"
#message 125 WIFI_NEW_PROFILE_MESSAGE "Nouveau Profil"
#message 126 WIFI_SET_ACTIVE_PROFILE_MESSAGE "Profil Actif"
#message 127 WIFI_MODIFY_PROFILE_MESSAGE "Modifier Profil"
#message 128 WIFI_REMOVE_PROFILE_MESSAGE "Supprimer Profil"
#message 129 WIFI_WEP_64_KEY_MESSAGE "Cle WEP 64"
#message 130 WIFI_WEP_128_KEY_MESSAGE "Cle WEP 128"
#message 131 WIFI_ENTER_10_DIGITS_MESSAGE "Saisissez 10 digits"
#message 132 WIFI_ENTER_26_DIGITS_MESSAGE "Saisissez 26 digits"
#message 133 WIFI_AVAILABLE_NETWORKS_MESSAGE "Reseaux Disponibles"
#message 134 WIFI_SCANNING_MESSAGE "Recherche en cours ..."
#message 135 WIFI_SELECT_NETWORK_MESSAGE "Choisissez un reseau"
#message 136 WIFI_CYPHER_MODE_MESSAGE "Chiffrement"
#message 137 WIFI_AUTH_MODE_MESSAGE "Authentification"
#message 138 WIFI_AUTH_MODE_OPEN_MESSAGE "Ouvert"
#message 139 WIFI_AUTH_MODE_SHARED_MESSAGE "Partage"
#message 140 WIFI_PASSPHRASE "Phrase de passe"
#message 141 BACK_LIGHT_DURATION "Duree Eclairage"
#message 142 STANDBY_DELAY "Delai avant veille"
#message 143 VALUE_BETWEEN_10_AND_120 "Valeur [10..1000]" 
#message 144 BLUETOOTH_CLEAR_SECRET "Efface Secret"
#message 145 EXCHANGE_TOTAL "Total  "
#message 146 BLUETOOTH_SET_BASE_NAME "Changer nom base"
#message 147 BLUETOOTH_BASE_NAME "Nom de la base"
#message 148 WIFI_IP_SETUP "Configuration IP"
#message 149 WIFI_ESSID_ENTRY "Saisie du SSID"
#message 150 COLOR_SETUP "Couleur"
#message 151 DISPLAY_COLOR "Couleur"
#message 152 DISPLAY_COLOR_TEXTE "Texte"
#message 153 DISPLAY_COLOR_FOND "Fond"
#message 154 GPRS_RETROFIT_MODE "Mode de retrofit GPRS"
#message 155 GPRS_RETROFIT_MODE_UMS "Cle USB"
#message 156 GPRS_RETROFIT_MODE_OLD "Ancienne ecole"
#message 157 GPRS_RETROFIT_RUNNING "En cours ..."
#message 158 ICON_MODEM_SETUP "MODEM"
#message 159 ICON_ETHERNET_SETUP "ETHERNET"
#message 160 ICON_BATTERY_SETUP "BATTERIE"
#message 161 ICON_RETROFIT_MASV2 "RETRO MAS V2"
#message 162 ICON_BLUETOOTH_SETUP "BASE"
#message 163 ICON_BASE_UPDATE "SOCLE"
#message 164 ICON_WIFI_SETUP_MESSAGE "WIFI"
#message 165 ICON_DISPLAY "ECRAN"
#message 166 HTML_FOOTER "prec. v ^ suiv."
#message 167 HTML_FOOTER_LEFT "Valider"
#message 168 HTML_FOOTER_RIGHT "Annuler"
#message 169 VALUE_BETWEEN_10_AND_59 "Valeur [10..59]"
#message 170 TITLE_BASE_UPDATE "Mise a Jour Base"
#message 171 MR40_STANDBY_SETUP_MSG "Configuration veille"
#message 172 MR40_STANDBY_TYPE_MSG "Type de veille"
#message 173 MR40_STANDBY_TYPE_NONE_MSG "Aucune"
#message 174 MR40_STANDBY_TYPE_LIGHT_MSG "Legere"
#message 175 MR40_STANDBY_TYPE_DEEP_MSG "Profonde"
#message 176 VALUE_BETWEEN_0_AND_900 "Valeur [0..900]"
#message 177 ENERGY_SAVE_TITLE "Gestion Energie"
#message 178 ENERGY_SAVE_ITEM_NONE "Aucune"
#message 179 ENERGY_SAVE_ITEM_BACKLIGHT "Retro-eclairage"
#message 180 ENERGY_SAVE_ITEM_LIGHT "Veille legere"
#message 181 ENERGY_SAVE_ITEM_DEEP "Veille Profonde"
#message 182 ICON_ENERGY_SETUP "Energie"
#message 183 TEXT_COLOUR "Couleur du texte"
#message 184 BACKGROUND_COLOUR "Couleur de fond"
#message 185 FUNCTION "Fonction"
#message 186 IMPOSSIBLE "Impossible"
#message 187 EXT_PRINTER "Imprimante"
#message 188 ICON_EXT_PRINTER "IMPRIMANTE"
#message 189 CRADLE_ADRESS "ADRESSE SOCLE"
#message 190 STANDBY_ON_CRADLE "Veille sur base"
#message 191 EXT_BT_PRINTER "BT Imprimante"
#message 192 EXT_BT_ADRESSE "Adresse"
#message 193 EXT_BT_ACTIVATION "Activer"
#message 194 EXT_BT_DESACTIVATION "Desactiver"
#message 195 EXT_CALIBRATION "Calibration"
#message 196 ICON_EXT_CALIBRATION "CALIBRATION"
#message 197 PROXY_SETUP "Proxy"
#message 198 ICON_PROXY_SETUP "PROXY"
#message 199 PROXY_USE_MESSAGE "Activer PROXY?"
#message 200 PROXY_IP_ADDRESS_MESSAGE "Adresse IP - Proxy"
#message 201 PROXY_PORT_MESSAGE "Port - Proxy"
#message 202 PROXY_LOGIN_MESSAGE "Login - Proxy"
#message 203 PROXY_PASSWORD_MESSAGE "Password - Proxy"
#message 204 PROXY_ITEM_SOCKS4 "SOCKS4"
#message 205 PROXY_ITEM_SOCKS5 "SOCKS5"
#message 206 CANCEL_QUESTION "Abandon ?"
#message 207 EXT_BT_PRINTER_KEEPALIVE "Maintien BT"
#message 208 PROXY_USE_AUTH "Authentification"
#message 209 PROXY_USER_ID_MESSAGE "User ID - Proxy"
#message 210 BARCODE_SETUP "BT Code Barre"
#message 211 ICON_BARCODE_SETUP "BT CODE BARRE"
#message 212 BT_STREAMING_SETUP "BT Audio"
#message 213 ICON_BT_STREAMING_SETUP "BT AUDIO"
#message 214 BT_INFORMATION_ITEM "Information"
#message 215 BT_DEVICES_TITLE "Appareils:"
#message 216 BT_NO_DEVICE_MESSAGE "Aucun Appareil"
#message 217 BT_NONE_MESSAGE "Aucun"
#message 218 BT_UNKNOWM_MESSAGE "Sans Nom"
#message 219 BT_DISCOVERY_ITEM "Recherche"
#message 220 BT_SCANNING_MESSAGE "Recherche"
#message 221 BT_UPDATE_ITEM "Rafraichir"
#message 222 BT_PINCODE "Code Pin"
#message 223 BT_PINCODE_2 "Code Pin : "
#message 224 BT_DISASSOCIATE "Désassociation"
#message 225 CANCEL_BUTTON "Abandon"
#message 226 LAST_MESSAGE ""

