// #LANGUAGE EN
// #FONFILE /LOCAL/MANAGER.SGN
// #MSGCODING ISO8859
// #CHARSET 1
// #FILETYPE 2
// #APPLITYPE 14
#message 0 MODEM_SETUP "Modem Setup"
#message 1 MODEM_OUTPUT_LEVEL "Output Level"
#message 2 MODEM_DTMF_TIMING "DTMF"
#message 3 MODEM_ADVANCED_SETTINGS "Advanced Settings"
#message 4 MODEM_PRINT "Print"
#message 5 MODEM_SAVE "Save"
#message 6 MODEM_QUIT "Quit"
#message 7 MODEM_LINE_TYPE "Line Selection"
#message 8 MODEM_LINE_TYPE_LONG "Long line"
#message 9 MODEM_LINE_TYPE_SHORT "Short Line"
#message 10 VALUE_BETWEEN_5_AND_30 "Value [5..30]"
#message 11 MODEM_MILLISECOND "Milliseconds"
#message 12 MODEM_STANDARD_RULE "Standard Rule"
#message 13 MODEM_BELOW_RULE "Below Rule"
#message 14 MODEM_ABOVE_RULE "Above Rule"
#message 15 BINARY_VALUE "Binary Value"
#message 16 MODEM_DEFAULT_SETUP "Default Setup"
#message 17 MODEM_RELOAD "Reload Setup"
#message 18 HARDWARE_SETUP "Hardware Setup"
#message 19 ETHERNET_SETUP "Ethernet Setup"
#message 20 ETHERNET_IP_ADDR "IP Address"
#message 21 ETHERNET_NET_MASK "Subnet Mask"
#message 22 ETHERNET_GATEWAY "Gateway"
#message 23 ETHERNET_BOOT_PROTO "Boot Proto"
#message 24 ETHERNET_PRINT "Print"
#message 25 ETHERNET_SAVE "Save"
#message 26 ETHERNET_QUIT "Quit"
#message 27 ETHERNET_RELOAD "Reload Setup"
#message 28 ETHERNET_STATIC "Static Address"
#message 29 ETHERNET_DHCP "DHCP"
#message 30 ETHERNET_BOOTP "BOOTP"
#message 31 MODEM_V22BIS_FORCED "Limited Speed"
#message 32 MODEM_CALIBRATION "Calibration"
#message 33 MODEM_SITE_CALIBRATION "Site Calibration"
#message 34 MODEM_TRY_CALIBRATION "Trying "
#message 35 MODEM_PLEASE_WAIT "Please wait"
#message 36 MODEM_STARTUP_KO "Startup KO"
#message 37 MODEM_START_CALIBRATION "Start Calibration"
#message 38 MODEM_KILL_CALIBRATION_FILE "Del Cali File"
#message 39 MODEM_PRINT_CALIBRATION_FILE "Print Cali File"
#message 40 MODEM_CALIBRATION_CHANGE_PAD_NUMBER "Change PAD Number"
#message 41 BATTERY_SETUP "Battery Setup"
#message 42 NEW_BATTERY "New Battery"
#message 43 SAVE_QUESTION "Save ?"
#message 44 ANSWER_YES "Yes"
#message 45 ANSWER_NO "No"
#message 46 DISCHARGE "Discharge"
#message 47 NEW_BATTERY_QUESTION "New Battery ?"
#message 48 FULL_DISCHARGE_QUESTION "Full Discharge ?"
#message 49 DISCHARGING "Discharging"
#message 50 BATTERY_LEVEL "Battery Level"
#message 51 ETHERNET_DNS_1 "DNS 1"
#message 52 ETHERNET_DNS_2 "DNS 2"
#message 53 BACK_LIGHT "Back Light"
#message 54 BRIGHTER "Brighter"
#message 55 DIMMER "Dimmer"
#message 56 ETHERNET_RESET_CONF "Reset Conf."
#message 57 START_ON_TILT "Tilt"
#message 58 USB_CHARGING "USB Charging"
#message 59 RETROFIT_MASV2 "Retrofit MASv2"
#message 60 RETROFIT_BLUETOOTH "Retrofit BlueTooth"
#message 61 BLUETOOTH_DRIVER_NOT_FOUND "BlueTooth driver" "\n" " not found"
#message 62 GPRS_DRIVER_NOT_FOUND "GPRS driver" "\n" " not found"
#message 63 GPRS_RETROFIT_BUSY "Retrofit GPRS" "\n" " Busy"
#message 64 GPRS_RETROFIT_NOT_IMPLEMENTED "Retrofit GPRS" "\n" " not Implemented"
#message 65 BLUETOOTH_RETROFIT_NOT_IMPLEMENTED "Cannot Retrofit" "\n" " BlueTooth"
#message 66 APPLICATION_NAME "Configuration"
#message 67 PLUS_ETHERNET "+Ethernet"
#message 68 PLUS_BATTERY "+Battery"
#message 69 PLUS_BLUETOOTH "+Bluetooth"
#message 70 PLUS_GPRS "+GPRS"
#message 71 NO_MODEM_OPTION "No MODEM option"
#message 72 PLUS_MODEM "+Modem"
#message 73 MODEM_NUMBER_OF_DAYS "Number of days"
#message 74 MODEM_NUMBER_OF_FAILURES "Number of failures"
#message 75 MODEM_LOOKUP_DEPTH "Lookup Depth"
#message 76 BLUETOOTH_SETUP "Cradle Setup"
#message 77 BLUETOOTH_ASSOCIATION "Association"
#message 78 BLUETOOTH_ADVANCED "Advanced"
#message 79 BLUETOOTH_EXPERT "Expert"
#message 80 BLUETOOTH_ASSOCIATION_NOT_IMPLEMENTED "Association" "\n" "not available"
#message 81 BLUETOOTH_NEW_BASE "New Base"
#message 82 BLUETOOTH_SELECT_BASE "Select Base"
#message 83 BLUETOOTH_REMOVE_BASE "Remove Base"
#message 84 IN_PROGRESS "In progress ..."
#message 85 BLUETOOTH_ASSOCIATION_SUCCESS "Association Successful"
#message 86 BLUETOOTH_ASSOCIATION_FAILURE "Association Failure"
#message 87 BLUETOOTH_PRINT_BASES "Print Bases"
#message 88 BLUETOOTH_NO_BASE "No known base"
#message 89 USER_ABORT "User Abort"
#message 90 NOT_ON_CRADLE "Not on cradle"
#message 91 PRINTER_NOT_SUPPORTED "Printer Not Supported"
#message 92 PRINTER_NOT_AVAILABLE "Printer Not Available"
#message 93 BATTERY_NOT_AVAILABLE "No Battery"
#message 94 BATTERY_NOT_COMPATIBLE "Battery NOT Compatible"
#message 95 BACK_ON_BASE "Put on cradle"
#message 96 WRONG_BT_DRIVER "Inconsistent Drivers"
#message 97 WRONG_BASE_FIRMWARE "Wrong Base Firmware"
#message 98 WRONG_PORTABLE_FIRMWARE "Wrong Portable Firmware"
#message 99 WRONG_FIRMWARES "Wrong Firmwares"
#message 100 MODEM_CURRENT_LIMITING "Current Limiting"
#message 101 ETHERNET_SPEED "Speed"
#message 102 ETHERNET_PING_IP_ADDRESS "Ping"
#message 103 ETHERNET_RECEIVED "Received"
#message 104 ETHERNET_WAITING_RESPONSE "Waiting Response..."
#message 105 BASE_UPDATE "Base Update"
#message 106 EXCHANGE_THIS_BASE "This Base (IR)"
#message 107 EXCHANGE_STATUS_IDLE "Idle"
#message 108 EXCHANGE_STATUS_CONNECTING "Connecting"
#message 109 EXCHANGE_STATUS_CONNECTED "Connected"
#message 110 EXCHANGE_STATUS_SENDING "Sending"
#message 111 EXCHANGE_STATUS_RECEIVING "Receiving"
#message 112 EXCHANGE_STATUS_ACTIVATING "Activating"
#message 113 EXCHANGE_STATUS_DISCONNECTING "Disconnecting"
#message 114 EXCHANGE_CURRENT "Current"
#message 115 BLUETOOTH_BASE_STATE "Base State"
#message 116 BACKLIGHT_ON_BASE "On-base backlight"
#message 117 BACKLIGHT_OUT_OF_BASE "Out-of-base backlight"
#message 118 DISPLAY_CONTRAST "Contrast"
#message 119 DISPLAY "Display"
#message 120 NEED_RESTART1 "This operation needs"
#message 121 NEED_RESTART2 "a restart ..."
#message 122 WIFI_SETUP_MESSAGE "Wifi Setup"
#message 123 WIFI_PROFILE_MESSAGE "Profiles"
#message 124 WIFI_INFO_MESSAGE "Infos"
#message 125 WIFI_NEW_PROFILE_MESSAGE "New Profile"
#message 126 WIFI_SET_ACTIVE_PROFILE_MESSAGE "Active Profile"
#message 127 WIFI_MODIFY_PROFILE_MESSAGE "Modifiy Profile"
#message 128 WIFI_REMOVE_PROFILE_MESSAGE "Remove Profile"
#message 129 WIFI_WEP_64_KEY_MESSAGE "WEP 64 Key"
#message 130 WIFI_WEP_128_KEY_MESSAGE "WEP 128 Key"
#message 131 WIFI_ENTER_10_DIGITS_MESSAGE "Enter 10 digits"
#message 132 WIFI_ENTER_26_DIGITS_MESSAGE "Enter 26 digits"
#message 133 WIFI_AVAILABLE_NETWORKS_MESSAGE "Available Networks"
#message 134 WIFI_SCANNING_MESSAGE "Scanning ..."
#message 135 WIFI_SELECT_NETWORK_MESSAGE "Select Network"
#message 136 WIFI_CYPHER_MODE_MESSAGE "Cypher"
#message 137 WIFI_AUTH_MODE_MESSAGE "Authentication"
#message 138 WIFI_AUTH_MODE_OPEN_MESSAGE "Open"
#message 139 WIFI_AUTH_MODE_SHARED_MESSAGE "Shared"
#message 140 WIFI_PASSPHRASE "Passphrase"
#message 141 BACK_LIGHT_DURATION "Backlight Duration"
#message 142 STANDBY_DELAY "Standby Delay"
#message 143 VALUE_BETWEEN_10_AND_120 "Value [10..1000]"
#message 144 BLUETOOTH_CLEAR_SECRET "Clear Secret"
#message 145 EXCHANGE_TOTAL "Total  "
#message 146 BLUETOOTH_SET_BASE_NAME "Set base name"
#message 147 BLUETOOTH_BASE_NAME "Base name"
#message 148 WIFI_IP_SETUP "IP Setup"
#message 149 WIFI_ESSID_ENTRY "ESSID entry"
#message 150 COLOR_SETUP "Color Setup"
#message 151 DISPLAY_COLOR "Color"
#message 152 DISPLAY_COLOR_TEXTE "Text"
#message 153 DISPLAY_COLOR_FOND "Bgrd"
#message 154 GPRS_RETROFIT_MODE "GPRS Retrofit Mode"
#message 155 GPRS_RETROFIT_MODE_UMS "USB Mass Storage"
#message 156 GPRS_RETROFIT_MODE_OLD "old School"
#message 157 GPRS_RETROFIT_RUNNING "Running ..."
#message 166 HTML_FOOTER "prev. v ^ next."
#message 167 HTML_FOOTER_LEFT "Validate"
#message 168 HTML_FOOTER_RIGHT "Cancel"
#message 169 VALUE_BETWEEN_10_AND_59 "Value [10..59]"
#message 170 TITLE_BASE_UPDATE "Base Update"
#message 171 MR40_STANDBY_SETUP_MSG "Standby setting"
#message 172 MR40_STANDBY_TYPE_MSG "Standby type"
#message 173 MR40_STANDBY_TYPE_NONE_MSG "None"
#message 174 MR40_STANDBY_TYPE_LIGHT_MSG "Light"
#message 175 MR40_STANDBY_TYPE_DEEP_MSG "Deep"
#message 176 VALUE_BETWEEN_0_AND_900 "Value [0..900]"
#message 177 ENERGY_SAVE_TITLE "Energy save"
#message 178 ENERGY_SAVE_ITEM_NONE "None"
#message 179 ENERGY_SAVE_ITEM_BACKLIGHT "Backlight"
#message 180 ENERGY_SAVE_ITEM_LIGHT "Light standby"
#message 181 ENERGY_SAVE_ITEM_DEEP "Deep standby"
#message 183 TEXT_COLOUR "Text colour"
#message 184 BACKGROUND_COLOUR "Background colour"
#message 185 FUNCTION "Function"
#message 186 IMPOSSIBLE "Unvailable"
#message 187 EXT_PRINTER "Printer"
#message 189 CRADLE_ADRESS "CRADLE ADDRESS"
#message 190 STANDBY_ON_CRADLE "Standby On Cradle"
#message 191 EXT_BT_PRINTER "BT Printer"
#message 192 EXT_BT_ADRESSE "Address"
#message 193 EXT_BT_ACTIVATION "Enable"
#message 194 EXT_BT_DESACTIVATION "Disable"
#message 195 EXT_CALIBRATION "Calibration"
#message 197 PROXY_SETUP "Proxy setup"
#message 199 PROXY_USE_MESSAGE "Use PROXY?"
#message 200 PROXY_IP_ADDRESS_MESSAGE "IP Address - Proxy"
#message 201 PROXY_PORT_MESSAGE "Port - Proxy"
#message 202 PROXY_LOGIN_MESSAGE "Login - Proxy"
#message 203 PROXY_PASSWORD_MESSAGE "Password - Proxy"
#message 204 PROXY_ITEM_SOCKS4 "SOCKS4"
#message 205 PROXY_ITEM_SOCKS5 "SOCKS5"
#message 206 CANCEL_QUESTION "Cancel ?"
#message 207 EXT_BT_PRINTER_KEEPALIVE "Keep Alive"
#message 208 PROXY_USE_AUTH "Use authentication"
#message 209 PROXY_USER_ID_MESSAGE "User ID - Proxy"
#message 210 BARCODE_SETUP "BT Barcode"
#message 212 BT_STREAMING_SETUP "BT Streaming"
#message 214 BT_INFORMATION_ITEM "Information"
#message 215 BT_DEVICES_TITLE "Devices:"
#message 216 BT_NO_DEVICE_MESSAGE "No device"
#message 217 BT_NONE_MESSAGE "None"
#message 218 BT_UNKNOWM_MESSAGE "No Name"
#message 219 BT_DISCOVERY_ITEM "Discovery"
#message 220 BT_SCANNING_MESSAGE "Scanning"
#message 221 BT_UPDATE_ITEM "Update"
#message 222 BT_PINCODE "Pincode"
#message 223 BT_PINCODE_2 "Code Pin : "
#message 224 BT_DISASSOCIATE "Remove"
#message 225 CANCEL_BUTTON "Cancel"
#message 226 START_ON_ORIENTATION "Flip"
#message 227 ORIENTATION_SETUP "Flip"
#message 228 APPLE_SPP_SETUP "BT Apple SPP"
#message 230 APPLE_IAP_SETUP "BT Apple IAP"
#message 232 PLEASE_WAIT "Please wait..."
#message 233 EXT_STYLET      "Stylet"
#message 235 DISPLAY_CONTRAST1 "'.' and UP keys"
#message 236 DISPLAY_CONTRAST2 "to increase value"
#message 237 DISPLAY_CONTRAST3 ".' and DOWN keys"
#message 238 DISPLAY_CONTRAST4 "to decrease value"
#message 239 LAST_MESSAGE ""
