/*!
 ------------------------------------------------------------------------------
INGENICO Technical Software Department
------------------------------------------------------------------------------
Copyright (c) 2013, Ingenico.
 28-32 boulevard de Grenelle 75015 Paris, France.
 All rights reserved.
 This source program is the property of INGENICO Company and may not be copied
 in any form or by any means, whether in part or in whole, except under license
 expressly granted by INGENICO company
 All copies of this program, whether in part or in whole, and
 whether modified or not, must display this and all other
 embedded copyright and ownership notices in full.
 ------------------------------------------------------------------------------
 Project : Telium+ (This file is automatically generated)
 Module : SDK
 This file allows T2 projects to use T+ renamed APIs and to have common code between T2 and T+ projects
 ------------------------------------------------------------------------------
*/

#ifdef __cplusplus
extern "C" {
#endif

#ifndef __SDK_COMPAT_SRC_TPLUS_H_INCLUDED__
#define __SDK_COMPAT_SRC_TPLUS_H_INCLUDED__

#ifdef __FRAMEWORK_TELIUM_2__

// Structures T2 redefined for T+
#undef Telium_Date_t
#define Telium_Date_t  DATE
#undef svc_callback
#define svc_callback  SAP
#undef svc_service_desc_t
#define svc_service_desc_t  service_desc_t
#undef Telium_File_t
#define Telium_File_t  FILE

// Defines T2 redefined for T+
#undef svc_callback
#define svc_callback  callback

// Functions T2 redefined for T+
#undef Telium_ServiceGet
#define Telium_ServiceGet  ServiceGet
#undef Telium_Powered
#define Telium_Powered  Powered
#undef Telium_Fclose
#define Telium_Fclose  fclose
#undef Telium_Output_command
#define Telium_Output_command  SV_output_command
#undef Telium_Kill
#define Telium_Kill  kill
#undef Telium_EMV_apdu
#define Telium_EMV_apdu  EMV_apdu
#undef Telium_ServiceRegister
#define Telium_ServiceRegister  ServiceRegister
#undef Telium_Fputc
#define Telium_Fputc  fputc
#undef Telium_InitMailBox
#define Telium_InitMailBox  OS_rtc_InitMailBox
#undef Telium_ChngEventFile
#define Telium_ChngEventFile  ChngEventFile
#undef Telium_Power_on_sync
#define Telium_Power_on_sync  power_on_sync
#undef Telium_Fwrite
#define Telium_Fwrite  fwrite
#undef Telium_Socket_send
#define Telium_Socket_send  send
#undef Telium_Fputs
#define Telium_Fputs  fputs
#undef Telium_Stdprt
#define Telium_Stdprt  stdprt
#undef Telium_Socket_write
#define Telium_Socket_write  writesocket
#undef Telium_GetErrno
#define Telium_GetErrno  GetErrno
#undef Telium_Power_on
#define Telium_Power_on  SV_power_on
#undef Telium_inet_ntoa
#define Telium_inet_ntoa  __inet_ntoa
#undef Telium_TestReceive
#define Telium_TestReceive  OS_rtc_TestReceive
#undef Telium_Socket_read
#define Telium_Socket_read  read
#undef Telium_ServiceRemove
#define Telium_ServiceRemove  ServiceRemove
#undef Telium_Send
#define Telium_Send  OS_rtc_Send
#undef Telium_Read_date
#define Telium_Read_date  read_date
#undef Telium_Socket_recvfrom
#define Telium_Socket_recvfrom  recvfrom
#undef Telium_Fbreak
#define Telium_Fbreak  fbreak
#undef Telium_Socket_sendto
#define Telium_Socket_sendto  sendto
#undef TM_GetTerminalType
#define TM_GetTerminalType  GetTerminalType
#undef Telium_ServiceCall
#define Telium_ServiceCall  ServiceCall
#undef Telium_Printf
#define Telium_Printf  printf
#undef Telium_Socket_connect
#define Telium_Socket_connect  connect
#undef Telium_Socket_getsockname
#define Telium_Socket_getsockname  getsockname
#undef Telium_Fgets
#define Telium_Fgets  fgets
#undef Telium_Socket_close
#define Telium_Socket_close  close
#undef Telium_GiveNoTask
#define Telium_GiveNoTask  GiveNoTask
#undef Telium_StopDelay
#define Telium_StopDelay  OS_rtc_StopDelay
#undef Telium_Fopen
#define Telium_Fopen  fopen
#undef Telium_Exit
#define Telium_Exit  exit
#undef Telium_inet_addr
#define Telium_inet_addr  __inet_addr
#undef Telium_Receive
#define Telium_Receive  OS_rtc_Receive
#undef Telium_StartLDelay
#define Telium_StartLDelay  OS_rtc_StartLDelay
#undef Telium_Ferror
#define Telium_Ferror  ferror
#undef Telium_Socket_read
#define Telium_Socket_read  readsocket
#undef Telium_gethostbyaddr_r
#define Telium_gethostbyaddr_r  gethostbyaddr_r
#undef Telium_Power_down
#define Telium_Power_down  SV_power_down
#undef Telium_Defdisplaypatterndsp
#define Telium_Defdisplaypatterndsp  defdisplaypatterndsp
#undef Telium_Stdout
#define Telium_Stdout  __STDOUT
#undef Telium_ServiceCall
#define Telium_ServiceCall  USR_ServiceCall
#undef Telium_EMV_power_on
#define Telium_EMV_power_on  EMV_power_on
#undef Telium_Fowner
#define Telium_Fowner  fowner
#undef Telium_Socket_getpeername
#define Telium_Socket_getpeername  getpeername
#undef Telium_Socket_recv
#define Telium_Socket_recv  recv
#undef Telium_Socket_setsockopt
#define Telium_Socket_setsockopt  setsockopt
#undef Telium_Putchar
#define Telium_Putchar  putchar
#undef Telium_Socket_socket
#define Telium_Socket_socket  socket
#undef Telium_EventsOccurred
#define Telium_EventsOccurred  OS_rtc_EventsOccurred
#undef Telium_SignalEvent
#define Telium_SignalEvent  OS_rtc_SignalEvent
#undef Telium_TestP
#define Telium_TestP  OS_rtc_TestP
#undef Telium_Send_receive
#define Telium_Send_receive  send_receive
#undef Telium_Socket_sendmsg
#define Telium_Socket_sendmsg  sendmsg
#undef Telium_Power_down
#define Telium_Power_down  power_down
#undef Telium_Socket_ioctl
#define Telium_Socket_ioctl  ioctlsocket
#undef Telium_Read_date
#define Telium_Read_date  SV_read_date
#undef Telium_Output_command
#define Telium_Output_command  output_command
#undef Telium_Input_command
#define Telium_Input_command  SV_input_command
#undef Telium_ClearEvents
#define Telium_ClearEvents  OS_rtc_ClearEvents
#undef Telium_Shutdown
#define Telium_Shutdown  shutdown
#undef Telium_Fioctl
#define Telium_Fioctl  fioctl
#undef Telium_inet_aton
#define Telium_inet_aton  __inet_aton
#undef Telium_P
#define Telium_P  OS_rtc_P
#undef Telium_V
#define Telium_V  OS_rtc_V
#undef Telium_Getchar
#define Telium_Getchar  getchar
#undef Telium_Socket_getsockopt
#define Telium_Socket_getsockopt  getsockopt
#undef Telium_Puts
#define Telium_Puts  puts
#undef Telium_Powered
#define Telium_Powered  powered
#undef Telium_ntohl
#define Telium_ntohl  ntohl
#undef Telium_TaskState
#define Telium_TaskState  OS_rtc_TaskState
#undef Telium_ntohs
#define Telium_ntohs  ntohs
#undef Telium_Putc
#define Telium_Putc  putc
#undef Telium_Input_command
#define Telium_Input_command  input_command
#undef Telium_Socket_close
#define Telium_Socket_close  closesocket
#undef Telium_Socket_listen
#define Telium_Socket_listen  listen
#undef Telium_Fork
#define Telium_Fork  fork
#undef Telium_Fread
#define Telium_Fread  fread
#undef Telium_Reset_buf
#define Telium_Reset_buf  reset_buf
#undef Telium_InitGkDrv
#define Telium_InitGkDrv  InitGkDrv
#undef Telium_gethostbyname_r
#define Telium_gethostbyname_r  gethostbyname_r
#undef Telium_Power_on
#define Telium_Power_on  power_on
#undef Telium_Power_down_sync
#define Telium_Power_down_sync  power_down_sync
#undef Telium_Stdperif
#define Telium_Stdperif  stdperif
#undef Telium_Terminate
#define Telium_Terminate  OS_rtc_Terminate
#undef Telium_Ungetc
#define Telium_Ungetc  ungetc
#undef Telium_Vsprintf
#define Telium_Vsprintf  vsprintf
#undef Telium_CopyFile
#define Telium_CopyFile  CopyFile
#undef Telium_InitSemaphore
#define Telium_InitSemaphore  OS_rtc_InitSemaphore
#undef Telium_htonl
#define Telium_htonl  htonl
#undef TMT_Retrieve_Clock
#define TMT_Retrieve_Clock  get_tick_counter
#undef Telium_Ctrl_date
#define Telium_Ctrl_date  ctrl_date
#undef Telium_Socket_accept
#define Telium_Socket_accept  accept
#undef Telium_Download
#define Telium_Download  download
#undef Telium_Fprintf
#define Telium_Fprintf  fprintf
#undef Telium_Is_iso1
#define Telium_Is_iso1  is_iso1
#undef Telium_Is_iso3
#define Telium_Is_iso3  is_iso3
#undef Telium_Is_iso2
#define Telium_Is_iso2  is_iso2
#undef Telium_Isbattery
#define Telium_Isbattery  isbattery
#undef Telium_Mask_event
#define Telium_Mask_event  mask_event
#undef Telium_Stdin
#define Telium_Stdin  __STDIN
#undef Telium_Clearerr
#define Telium_Clearerr  clearerr
#undef Telium_Pprintf
#define Telium_Pprintf  pprintf
#undef Telium_Getc
#define Telium_Getc  getc
#undef Telium_Socket_shutdown
#define Telium_Socket_shutdown  shutdownsocket
#undef Telium_Socket_write
#define Telium_Socket_write  write
#undef Telium_Socket_recvmsg
#define Telium_Socket_recvmsg  recvmsg
#undef Telium_Status
#define Telium_Status  status
#undef Telium_FormatOem
#define Telium_FormatOem  FormatOem
#undef Telium_SetErrno
#define Telium_SetErrno  SetErrno
#undef Telium_Ttestall
#define Telium_Ttestall  ttestall
#undef Telium_Mask_event_read
#define Telium_Mask_event_read  mask_event_read
#undef Telium_WaitEvents
#define Telium_WaitEvents  OS_rtc_WaitEvents
#undef Telium_Systemfioctl
#define Telium_Systemfioctl  SystemFioctl
#undef Telium_Socket_bind
#define Telium_Socket_bind  bind
#undef Telium_htons
#define Telium_htons  htons
#undef Telium_Socket_select
#define Telium_Socket_select  selectsocket
#undef Telium_CurrentTask
#define Telium_CurrentTask  OS_rtc_CurrentTask
#undef Telium_Defdisplaypattern
#define Telium_Defdisplaypattern  defdisplaypattern
#undef Telium_Exit
#define Telium_Exit  OEM_exit

#endif //__FRAMEWORK_TELIUM_2__

#endif   //__SDK_COMPAT_SRC_TPLUS_H_INCLUDED__

#ifdef __cplusplus
}
#endif

